/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dddexp3_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* VecToso3:(i0[3])->(o0[3x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, *w5=w+9, *w6=w+12, *w7=w+21;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @4 = horzcat(@0, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #6: @4 = @4' */
  /* #7: @0 = @1[2] */
  for (rr=(&w0), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #8: @2 = 0 */
  w2 = 0.;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (-@3) */
  w3 = (- w3 );
  /* #11: @5 = horzcat(@0, @2, @3) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @5 = @5' */
  /* #13: @0 = @1[1] */
  for (rr=(&w0), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @0 = (-@0) */
  w0 = (- w0 );
  /* #15: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @3 = 0 */
  w3 = 0.;
  /* #17: @1 = horzcat(@0, @2, @3) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #18: @1 = @1' */
  /* #19: @6 = horzcat(@4, @5, @1) */
  rr=w6;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #20: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

/* dddexp3:(i0[3],i1[3],i2[3],i3[3])->(o0[3x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+4, *cr, *cs;
  casadi_real *w0=w+30, w1, w2, w3, *w4=w+36, *w5=w+39, *w6=w+48, *w7=w+57, *w8=w+60, *w9=w+69, *w10=w+72, *w11=w+81, w12, w13, w14, w15, *w16=w+94, *w17=w+97, *w18=w+106, *w19=w+115, w20;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(3, w0, w0));
  /* #2: @2 = 2.22045e-16 */
  w2 = 2.2204460492503131e-16;
  /* #3: @2 = (@1<@2) */
  w2  = (w1<w2);
  /* #4: @3 = 0.5 */
  w3 = 5.0000000000000000e-01;
  /* #5: @4 = input[3][0] */
  casadi_copy(arg[3], 3, w4);
  /* #6: @5 = VecToso3(@4) */
  arg1[0]=w4;
  res1[0]=w5;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #7: @5 = (@3*@5) */
  for (i=0, rr=w5, cs=w5; i<9; ++i) (*rr++)  = (w3*(*cs++));
  /* #8: @3 = 0.166667 */
  w3 = 1.6666666666666666e-01;
  /* #9: @6 = zeros(3x3) */
  casadi_clear(w6, 9);
  /* #10: @7 = input[1][0] */
  casadi_copy(arg[1], 3, w7);
  /* #11: @8 = VecToso3(@7) */
  arg1[0]=w7;
  res1[0]=w8;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #12: @9 = input[2][0] */
  casadi_copy(arg[2], 3, w9);
  /* #13: @10 = VecToso3(@9) */
  arg1[0]=w9;
  res1[0]=w10;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #14: @6 = mac(@8,@10,@6) */
  for (i=0, rr=w6; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #15: @8 = zeros(3x3) */
  casadi_clear(w8, 9);
  /* #16: @10 = VecToso3(@9) */
  arg1[0]=w9;
  res1[0]=w10;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #17: @11 = VecToso3(@7) */
  arg1[0]=w7;
  res1[0]=w11;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #18: @8 = mac(@10,@11,@8) */
  for (i=0, rr=w8; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w10+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #19: @6 = (@6+@8) */
  for (i=0, rr=w6, cs=w8; i<9; ++i) (*rr++) += (*cs++);
  /* #20: @6 = (@3*@6) */
  for (i=0, rr=w6, cs=w6; i<9; ++i) (*rr++)  = (w3*(*cs++));
  /* #21: @5 = (@5+@6) */
  for (i=0, rr=w5, cs=w6; i<9; ++i) (*rr++) += (*cs++);
  /* #22: @5 = (@2?@5:0) */
  for (i=0, rr=w5, cs=w5; i<9; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #23: @2 = (!@2) */
  w2 = (! w2 );
  /* #24: @3 = 2 */
  w3 = 2.;
  /* #25: @3 = (@1/@3) */
  w3  = (w1/w3);
  /* #26: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #27: @12 = 2 */
  w12 = 2.;
  /* #28: @12 = (@1/@12) */
  w12  = (w1/w12);
  /* #29: @3 = (@3/@12) */
  w3 /= w12;
  /* #30: @12 = sq(@3) */
  w12 = casadi_sq( w3 );
  /* #31: @13 = 2 */
  w13 = 2.;
  /* #32: @13 = (@12/@13) */
  w13  = (w12/w13);
  /* #33: @6 = VecToso3(@4) */
  arg1[0]=w4;
  res1[0]=w6;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #34: @14 = 0 */
  w14 = 0.;
  /* #35: @15 = 0 */
  w15 = 0.;
  /* #36: @16 = @0' */
  casadi_copy(w0, 3, w16);
  /* #37: @15 = mac(@16,@9,@15) */
  for (i=0, rr=(&w15); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #38: @16 = @0' */
  casadi_copy(w0, 3, w16);
  /* #39: @16 = (@15*@16) */
  for (i=0, rr=w16, cs=w16; i<3; ++i) (*rr++)  = (w15*(*cs++));
  /* #40: @14 = mac(@16,@7,@14) */
  for (i=0, rr=(&w14); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #41: @15 = sq(@1) */
  w15 = casadi_sq( w1 );
  /* #42: @14 = (@14/@15) */
  w14 /= w15;
  /* #43: @8 = VecToso3(@0) */
  arg1[0]=w0;
  res1[0]=w8;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #44: @10 = (@14*@8) */
  for (i=0, rr=w10, cs=w8; i<9; ++i) (*rr++)  = (w14*(*cs++));
  /* #45: @10 = (@6-@10) */
  for (i=0, rr=w10, cr=w6, cs=w10; i<9; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #46: @10 = (@13*@10) */
  for (i=0, rr=w10, cs=w10; i<9; ++i) (*rr++)  = (w13*(*cs++));
  /* #47: @13 = 1 */
  w13 = 1.;
  /* #48: @15 = 2 */
  w15 = 2.;
  /* #49: @15 = (@1/@15) */
  w15  = (w1/w15);
  /* #50: @15 = cos(@15) */
  w15 = cos( w15 );
  /* #51: @3 = (@3*@15) */
  w3 *= w15;
  /* #52: @13 = (@13-@3) */
  w13 -= w3;
  /* #53: @15 = sq(@1) */
  w15 = casadi_sq( w1 );
  /* #54: @13 = (@13/@15) */
  w13 /= w15;
  /* #55: @11 = zeros(3x3) */
  casadi_clear(w11, 9);
  /* #56: @11 = mac(@6,@8,@11) */
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #57: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #58: @17 = mac(@8,@6,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #59: @11 = (@11+@17) */
  for (i=0, rr=w11, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #60: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #61: @6 = VecToso3(@9) */
  arg1[0]=w9;
  res1[0]=w6;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #62: @18 = VecToso3(@7) */
  arg1[0]=w7;
  res1[0]=w18;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #63: @17 = mac(@6,@18,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #64: @19 = zeros(3x3) */
  casadi_clear(w19, 9);
  /* #65: @19 = mac(@18,@6,@19) */
  for (i=0, rr=w19; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #66: @17 = (@17+@19) */
  for (i=0, rr=w17, cs=w19; i<9; ++i) (*rr++) += (*cs++);
  /* #67: @11 = (@11+@17) */
  for (i=0, rr=w11, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #68: @17 = (@14*@8) */
  for (i=0, rr=w17, cs=w8; i<9; ++i) (*rr++)  = (w14*(*cs++));
  /* #69: @11 = (@11+@17) */
  for (i=0, rr=w11, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #70: @11 = (@13*@11) */
  for (i=0, rr=w11, cs=w11; i<9; ++i) (*rr++)  = (w13*(*cs++));
  /* #71: @10 = (@10+@11) */
  for (i=0, rr=w10, cs=w11; i<9; ++i) (*rr++) += (*cs++);
  /* #72: @3 = (@3-@12) */
  w3 -= w12;
  /* #73: @15 = sq(@1) */
  w15 = casadi_sq( w1 );
  /* #74: @3 = (@3/@15) */
  w3 /= w15;
  /* #75: @15 = 0 */
  w15 = 0.;
  /* #76: @16 = @0' */
  casadi_copy(w0, 3, w16);
  /* #77: @15 = mac(@16,@9,@15) */
  for (i=0, rr=(&w15); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #78: @11 = (@15*@18) */
  for (i=0, rr=w11, cs=w18; i<9; ++i) (*rr++)  = (w15*(*cs++));
  /* #79: @15 = 0 */
  w15 = 0.;
  /* #80: @16 = @0' */
  casadi_copy(w0, 3, w16);
  /* #81: @15 = mac(@16,@7,@15) */
  for (i=0, rr=(&w15); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #82: @17 = (@15*@6) */
  for (i=0, rr=w17, cs=w6; i<9; ++i) (*rr++)  = (w15*(*cs++));
  /* #83: @11 = (@11+@17) */
  for (i=0, rr=w11, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #84: @15 = 0 */
  w15 = 0.;
  /* #85: @16 = @7' */
  casadi_copy(w7, 3, w16);
  /* #86: @15 = mac(@16,@9,@15) */
  for (i=0, rr=(&w15); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #87: @20 = 0 */
  w20 = 0.;
  /* #88: @16 = @0' */
  casadi_copy(w0, 3, w16);
  /* #89: @20 = mac(@16,@4,@20) */
  for (i=0, rr=(&w20); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w4+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #90: @15 = (@15+@20) */
  w15 += w20;
  /* #91: @20 = 4 */
  w20 = 4.;
  /* #92: @20 = (@20*@14) */
  w20 *= w14;
  /* #93: @20 = (@15-@20) */
  w20  = (w15-w20);
  /* #94: @17 = (@20*@8) */
  for (i=0, rr=w17, cs=w8; i<9; ++i) (*rr++)  = (w20*(*cs++));
  /* #95: @11 = (@11+@17) */
  for (i=0, rr=w11, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #96: @11 = (@3*@11) */
  for (i=0, rr=w11, cs=w11; i<9; ++i) (*rr++)  = (w3*(*cs++));
  /* #97: @10 = (@10+@11) */
  for (i=0, rr=w10, cs=w11; i<9; ++i) (*rr++) += (*cs++);
  /* #98: @3 = 2 */
  w3 = 2.;
  /* #99: @12 = (@12/@3) */
  w12 /= w3;
  /* #100: @3 = 3 */
  w3 = 3.;
  /* #101: @3 = (@3*@13) */
  w3 *= w13;
  /* #102: @12 = (@12-@3) */
  w12 -= w3;
  /* #103: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #104: @12 = (@12/@1) */
  w12 /= w1;
  /* #105: @1 = 0 */
  w1 = 0.;
  /* #106: @16 = @0' */
  casadi_copy(w0, 3, w16);
  /* #107: @1 = mac(@16,@9,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #108: @11 = zeros(3x3) */
  casadi_clear(w11, 9);
  /* #109: @11 = mac(@8,@18,@11) */
  for (i=0, rr=w11; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w18+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #110: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #111: @17 = mac(@18,@8,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w18+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #112: @11 = (@11+@17) */
  for (i=0, rr=w11, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #113: @11 = (@1*@11) */
  for (i=0, rr=w11, cs=w11; i<9; ++i) (*rr++)  = (w1*(*cs++));
  /* #114: @1 = 0 */
  w1 = 0.;
  /* #115: @0 = @0' */
  /* #116: @1 = mac(@0,@7,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w0+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #117: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #118: @17 = mac(@8,@6,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #119: @18 = zeros(3x3) */
  casadi_clear(w18, 9);
  /* #120: @18 = mac(@6,@8,@18) */
  for (i=0, rr=w18; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w6+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #121: @17 = (@17+@18) */
  for (i=0, rr=w17, cs=w18; i<9; ++i) (*rr++) += (*cs++);
  /* #122: @17 = (@1*@17) */
  for (i=0, rr=w17, cs=w17; i<9; ++i) (*rr++)  = (w1*(*cs++));
  /* #123: @11 = (@11+@17) */
  for (i=0, rr=w11, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #124: @1 = 5 */
  w1 = 5.;
  /* #125: @1 = (@1*@14) */
  w1 *= w14;
  /* #126: @15 = (@15-@1) */
  w15 -= w1;
  /* #127: @17 = zeros(3x3) */
  casadi_clear(w17, 9);
  /* #128: @17 = mac(@8,@8,@17) */
  for (i=0, rr=w17; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w8+j, tt=w8+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #129: @17 = (@15*@17) */
  for (i=0, rr=w17, cs=w17; i<9; ++i) (*rr++)  = (w15*(*cs++));
  /* #130: @11 = (@11+@17) */
  for (i=0, rr=w11, cs=w17; i<9; ++i) (*rr++) += (*cs++);
  /* #131: @11 = (@12*@11) */
  for (i=0, rr=w11, cs=w11; i<9; ++i) (*rr++)  = (w12*(*cs++));
  /* #132: @10 = (@10+@11) */
  for (i=0, rr=w10, cs=w11; i<9; ++i) (*rr++) += (*cs++);
  /* #133: @10 = (@2?@10:0) */
  for (i=0, rr=w10, cs=w10; i<9; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #134: @5 = (@5+@10) */
  for (i=0, rr=w5, cs=w10; i<9; ++i) (*rr++) += (*cs++);
  /* #135: output[0][0] = @5 */
  casadi_copy(w5, 9, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int dddexp3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dddexp3_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dddexp3_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dddexp3_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dddexp3_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dddexp3_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dddexp3_incref(void) {
}

CASADI_SYMBOL_EXPORT void dddexp3_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dddexp3_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int dddexp3_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dddexp3_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dddexp3_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dddexp3_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dddexp3_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    case 3: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dddexp3_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dddexp3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 125;
  return 0;
}

CASADI_SYMBOL_EXPORT int dddexp3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 125*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_dddexp3(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[146];
  casadi_int *iw = 0;
  const casadi_real* arg[8] = {0};
  casadi_real* res[3] = {0};
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"dddexp3\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"dddexp3\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+21);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+3, casadi_s0, w+21);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+6, casadi_s0, w+21);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+9, casadi_s0, w+21);
  --resc;
  res[0] = w+12;
  dddexp3_incref();
  mem = dddexp3_checkout();
  i = dddexp3(arg, res, iw, w+21, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"dddexp3\" failed.");
  dddexp3_release(mem);
  dddexp3_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[8];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_dddexp3(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "dddexp3")==0) {
    mex_dddexp3(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'dddexp3'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
