/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) ddexp3_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};

/* VecToso3:(i0[3])->(o0[3x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, *w5=w+9, *w6=w+12, *w7=w+21;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @4 = horzcat(@0, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #6: @4 = @4' */
  /* #7: @0 = @1[2] */
  for (rr=(&w0), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #8: @2 = 0 */
  w2 = 0.;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (-@3) */
  w3 = (- w3 );
  /* #11: @5 = horzcat(@0, @2, @3) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @5 = @5' */
  /* #13: @0 = @1[1] */
  for (rr=(&w0), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @0 = (-@0) */
  w0 = (- w0 );
  /* #15: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @3 = 0 */
  w3 = 0.;
  /* #17: @1 = horzcat(@0, @2, @3) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #18: @1 = @1' */
  /* #19: @6 = horzcat(@4, @5, @1) */
  rr=w6;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #20: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

/* ddexp3:(i0[3],i1[3])->(o0[3x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+2, *cs;
  casadi_real w0, *w1=w+31, w2, w3, w4, w5, *w6=w+38, *w7=w+41, w8, *w9=w+51, *w10=w+60, *w11=w+69, *w12=w+78, *w13=w+87;
  /* #0: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = ||@1||_F */
  w2 = sqrt(casadi_dot(3, w1, w1));
  /* #3: @0 = (@0<=@2) */
  w0  = (w0<=w2);
  /* #4: @3 = 2 */
  w3 = 2.;
  /* #5: @3 = (@2/@3) */
  w3  = (w2/w3);
  /* #6: @3 = sin(@3) */
  w3 = sin( w3 );
  /* #7: @4 = 2 */
  w4 = 2.;
  /* #8: @4 = (@2/@4) */
  w4  = (w2/w4);
  /* #9: @3 = (@3/@4) */
  w3 /= w4;
  /* #10: @4 = sq(@3) */
  w4 = casadi_sq( w3 );
  /* #11: @5 = 2 */
  w5 = 2.;
  /* #12: @5 = (@4/@5) */
  w5  = (w4/w5);
  /* #13: @6 = input[1][0] */
  casadi_copy(arg[1], 3, w6);
  /* #14: @7 = VecToso3(@6) */
  arg1[0]=w6;
  res1[0]=w7;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #15: @7 = (@5*@7) */
  for (i=0, rr=w7, cs=w7; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #16: @5 = 1 */
  w5 = 1.;
  /* #17: @8 = 2 */
  w8 = 2.;
  /* #18: @8 = (@2/@8) */
  w8  = (w2/w8);
  /* #19: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #20: @3 = (@3*@8) */
  w3 *= w8;
  /* #21: @5 = (@5-@3) */
  w5 -= w3;
  /* #22: @8 = sq(@2) */
  w8 = casadi_sq( w2 );
  /* #23: @5 = (@5/@8) */
  w5 /= w8;
  /* #24: @9 = zeros(3x3) */
  casadi_clear(w9, 9);
  /* #25: @10 = VecToso3(@6) */
  arg1[0]=w6;
  res1[0]=w10;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #26: @11 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w11;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #27: @9 = mac(@10,@11,@9) */
  for (i=0, rr=w9; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w10+j, tt=w11+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #28: @10 = zeros(3x3) */
  casadi_clear(w10, 9);
  /* #29: @11 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w11;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #30: @12 = VecToso3(@6) */
  arg1[0]=w6;
  res1[0]=w12;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #31: @10 = mac(@11,@12,@10) */
  for (i=0, rr=w10; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w11+j, tt=w12+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #32: @9 = (@9+@10) */
  for (i=0, rr=w9, cs=w10; i<9; ++i) (*rr++) += (*cs++);
  /* #33: @9 = (@5*@9) */
  for (i=0, rr=w9, cs=w9; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #34: @7 = (@7+@9) */
  for (i=0, rr=w7, cs=w9; i<9; ++i) (*rr++) += (*cs++);
  /* #35: @5 = (@3-@4) */
  w5  = (w3-w4);
  /* #36: @8 = sq(@2) */
  w8 = casadi_sq( w2 );
  /* #37: @5 = (@5/@8) */
  w5 /= w8;
  /* #38: @8 = 0 */
  w8 = 0.;
  /* #39: @13 = @1' */
  casadi_copy(w1, 3, w13);
  /* #40: @8 = mac(@13,@6,@8) */
  for (i=0, rr=(&w8); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w13+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #41: @5 = (@5*@8) */
  w5 *= w8;
  /* #42: @9 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w9;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #43: @9 = (@5*@9) */
  for (i=0, rr=w9, cs=w9; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #44: @7 = (@7+@9) */
  for (i=0, rr=w7, cs=w9; i<9; ++i) (*rr++) += (*cs++);
  /* #45: @9 = zeros(3x3) */
  casadi_clear(w9, 9);
  /* #46: @5 = 3 */
  w5 = 3.;
  /* #47: @8 = 1 */
  w8 = 1.;
  /* #48: @8 = (@8-@3) */
  w8 -= w3;
  /* #49: @5 = (@5*@8) */
  w5 *= w8;
  /* #50: @8 = sq(@2) */
  w8 = casadi_sq( w2 );
  /* #51: @5 = (@5/@8) */
  w5 /= w8;
  /* #52: @8 = 2 */
  w8 = 2.;
  /* #53: @4 = (@4/@8) */
  w4 /= w8;
  /* #54: @5 = (@5-@4) */
  w5 -= w4;
  /* #55: @4 = sq(@2) */
  w4 = casadi_sq( w2 );
  /* #56: @5 = (@5/@4) */
  w5 /= w4;
  /* #57: @4 = 0 */
  w4 = 0.;
  /* #58: @13 = @1' */
  casadi_copy(w1, 3, w13);
  /* #59: @4 = mac(@13,@6,@4) */
  for (i=0, rr=(&w4); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w13+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #60: @5 = (@5*@4) */
  w5 *= w4;
  /* #61: @10 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w10;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #62: @11 = (@5*@10) */
  for (i=0, rr=w11, cs=w10; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #63: @9 = mac(@11,@10,@9) */
  for (i=0, rr=w9; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w11+j, tt=w10+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #64: @7 = (@7-@9) */
  for (i=0, rr=w7, cs=w9; i<9; ++i) (*rr++) -= (*cs++);
  /* #65: @7 = (@0?@7:0) */
  for (i=0, rr=w7, cs=w7; i<9; ++i) (*rr++)  = (w0?cs[i]:0);
  /* #66: @0 = (!@0) */
  w0 = (! w0 );
  /* #67: @5 = 2.22045e-16 */
  w5 = 2.2204460492503131e-16;
  /* #68: @2 = (@2<@5) */
  w2  = (w2<w5);
  /* #69: @5 = 0.5 */
  w5 = 5.0000000000000000e-01;
  /* #70: @9 = VecToso3(@6) */
  arg1[0]=w6;
  res1[0]=w9;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #71: @9 = (@5*@9) */
  for (i=0, rr=w9, cs=w9; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #72: @9 = (@2?@9:0) */
  for (i=0, rr=w9, cs=w9; i<9; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #73: @9 = (@0?@9:0) */
  for (i=0, rr=w9, cs=w9; i<9; ++i) (*rr++)  = (w0?cs[i]:0);
  /* #74: @7 = (@7+@9) */
  for (i=0, rr=w7, cs=w9; i<9; ++i) (*rr++) += (*cs++);
  /* #75: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int ddexp3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int ddexp3_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int ddexp3_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ddexp3_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int ddexp3_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void ddexp3_release(int mem) {
}

CASADI_SYMBOL_EXPORT void ddexp3_incref(void) {
}

CASADI_SYMBOL_EXPORT void ddexp3_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int ddexp3_n_in(void) { return 2;}

CASADI_SYMBOL_EXPORT casadi_int ddexp3_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real ddexp3_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ddexp3_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* ddexp3_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ddexp3_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* ddexp3_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int ddexp3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 90;
  return 0;
}

CASADI_SYMBOL_EXPORT int ddexp3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 90*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_ddexp3(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[105];
  casadi_int *iw = 0;
  const casadi_real* arg[6] = {0};
  casadi_real* res[3] = {0};
  if (argc>2) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"ddexp3\" failed. Too many input arguments (%d, max 2)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"ddexp3\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+15);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+3, casadi_s0, w+15);
  --resc;
  res[0] = w+6;
  ddexp3_incref();
  mem = ddexp3_checkout();
  i = ddexp3(arg, res, iw, w+15, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"ddexp3\" failed.");
  ddexp3_release(mem);
  ddexp3_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[7];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_ddexp3(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "ddexp3")==0) {
    mex_ddexp3(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'ddexp3'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
