/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dexp6_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* VecToso3:(i0[3])->(o0[3x3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, *w5=w+9, *w6=w+12, *w7=w+21;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @4 = horzcat(@0, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #6: @4 = @4' */
  /* #7: @0 = @1[2] */
  for (rr=(&w0), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #8: @2 = 0 */
  w2 = 0.;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (-@3) */
  w3 = (- w3 );
  /* #11: @5 = horzcat(@0, @2, @3) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @5 = @5' */
  /* #13: @0 = @1[1] */
  for (rr=(&w0), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @0 = (-@0) */
  w0 = (- w0 );
  /* #15: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @3 = 0 */
  w3 = 0.;
  /* #17: @1 = horzcat(@0, @2, @3) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #18: @1 = @1' */
  /* #19: @6 = horzcat(@4, @5, @1) */
  rr=w6;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #20: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

/* dexp3:(i0[3])->(o0[3x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+30, w1, w2, *w3=w+35, *w4=w+44, w5, w6, *w7=w+55, *w8=w+64;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(3, w0, w0));
  /* #2: @2 = 2.22045e-16 */
  w2 = 2.2204460492503131e-16;
  /* #3: @2 = (@1<@2) */
  w2  = (w1<w2);
  /* #4: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #5: @3 = (@2?@3:0) */
  for (i=0, rr=w3, cs=w3; i<9; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #6: @2 = (!@2) */
  w2 = (! w2 );
  /* #7: @4 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w4);
  /* #8: @5 = 2 */
  w5 = 2.;
  /* #9: @5 = (@1/@5) */
  w5  = (w1/w5);
  /* #10: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #11: @6 = 2 */
  w6 = 2.;
  /* #12: @6 = (@1/@6) */
  w6  = (w1/w6);
  /* #13: @5 = (@5/@6) */
  w5 /= w6;
  /* #14: @5 = sq(@5) */
  w5 = casadi_sq( w5 );
  /* #15: @7 = VecToso3(@0) */
  arg1[0]=w0;
  res1[0]=w7;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #16: @8 = (@5*@7) */
  for (i=0, rr=w8, cs=w7; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #17: @4 = (@4+@8) */
  for (i=0, rr=w4, cs=w8; i<9; ++i) (*rr++) += (*cs++);
  /* #18: @5 = 1 */
  w5 = 1.;
  /* #19: @6 = 2 */
  w6 = 2.;
  /* #20: @6 = (@1/@6) */
  w6  = (w1/w6);
  /* #21: @6 = cos(@6) */
  w6 = cos( w6 );
  /* #22: @5 = (@5-@6) */
  w5 -= w6;
  /* #23: @8 = zeros(3x3) */
  casadi_clear(w8, 9);
  /* #24: @8 = mac(@7,@7,@8) */
  for (i=0, rr=w8; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w7+j, tt=w7+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #25: @8 = (@5*@8) */
  for (i=0, rr=w8, cs=w8; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #26: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #27: @8 = (@8/@1) */
  for (i=0, rr=w8; i<9; ++i) (*rr++) /= w1;
  /* #28: @4 = (@4+@8) */
  for (i=0, rr=w4, cs=w8; i<9; ++i) (*rr++) += (*cs++);
  /* #29: @4 = (@2?@4:0) */
  for (i=0, rr=w4, cs=w4; i<9; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #30: @3 = (@3+@4) */
  for (i=0, rr=w3, cs=w4; i<9; ++i) (*rr++) += (*cs++);
  /* #31: output[0][0] = @3 */
  casadi_copy(w3, 9, res[0]);
  return 0;
}

/* VecToso3:(i0[3])->(o0[3x3]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, *w5=w+9, *w6=w+12, *w7=w+21;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @4 = horzcat(@0, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #6: @4 = @4' */
  /* #7: @0 = @1[2] */
  for (rr=(&w0), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #8: @2 = 0 */
  w2 = 0.;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (-@3) */
  w3 = (- w3 );
  /* #11: @5 = horzcat(@0, @2, @3) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @5 = @5' */
  /* #13: @0 = @1[1] */
  for (rr=(&w0), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @0 = (-@0) */
  w0 = (- w0 );
  /* #15: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @3 = 0 */
  w3 = 0.;
  /* #17: @1 = horzcat(@0, @2, @3) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #18: @1 = @1' */
  /* #19: @6 = horzcat(@4, @5, @1) */
  rr=w6;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #20: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

/* dexp6:(i0[6])->(o0[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+73, *w1=w+79, *w2=w+82, w3, w4, w5, *w6=w+94, *w7=w+97, w8, w9, *w10=w+108, w11, *w12=w+118, *w13=w+127, *w14=w+136, *w15=w+145, *w16=w+154, *w17=w+157, *w18=w+175, *w19=w+193, *w20=w+211, *w21=w+247;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w0);
  /* #1: @1 = @0[3:6] */
  for (rr=w1, ss=w0+3; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #2: @2 = dexp3(@1) */
  arg1[0]=w1;
  res1[0]=w2;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #3: @3 = ||@1||_F */
  w3 = sqrt(casadi_dot(3, w1, w1));
  /* #4: @4 = 2.22045e-16 */
  w4 = 2.2204460492503131e-16;
  /* #5: @4 = (@3<@4) */
  w4  = (w3<w4);
  /* #6: @5 = 0.5 */
  w5 = 5.0000000000000000e-01;
  /* #7: @6 = @0[:3] */
  for (rr=w6, ss=w0+0; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #8: @7 = VecToso3(@6) */
  arg1[0]=w6;
  res1[0]=w7;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #9: @7 = (@5*@7) */
  for (i=0, rr=w7, cs=w7; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #10: @7 = (@4?@7:0) */
  for (i=0, rr=w7, cs=w7; i<9; ++i) (*rr++)  = (w4?cs[i]:0);
  /* #11: @4 = (!@4) */
  w4 = (! w4 );
  /* #12: @5 = 2 */
  w5 = 2.;
  /* #13: @5 = (@3/@5) */
  w5  = (w3/w5);
  /* #14: @5 = sin(@5) */
  w5 = sin( w5 );
  /* #15: @8 = 2 */
  w8 = 2.;
  /* #16: @8 = (@3/@8) */
  w8  = (w3/w8);
  /* #17: @5 = (@5/@8) */
  w5 /= w8;
  /* #18: @8 = sq(@5) */
  w8 = casadi_sq( w5 );
  /* #19: @9 = 2 */
  w9 = 2.;
  /* #20: @9 = (@8/@9) */
  w9  = (w8/w9);
  /* #21: @10 = VecToso3(@6) */
  arg1[0]=w6;
  res1[0]=w10;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #22: @10 = (@9*@10) */
  for (i=0, rr=w10, cs=w10; i<9; ++i) (*rr++)  = (w9*(*cs++));
  /* #23: @9 = 1 */
  w9 = 1.;
  /* #24: @11 = 2 */
  w11 = 2.;
  /* #25: @11 = (@3/@11) */
  w11  = (w3/w11);
  /* #26: @11 = cos(@11) */
  w11 = cos( w11 );
  /* #27: @5 = (@5*@11) */
  w5 *= w11;
  /* #28: @9 = (@9-@5) */
  w9 -= w5;
  /* #29: @11 = sq(@3) */
  w11 = casadi_sq( w3 );
  /* #30: @9 = (@9/@11) */
  w9 /= w11;
  /* #31: @12 = zeros(3x3) */
  casadi_clear(w12, 9);
  /* #32: @13 = VecToso3(@6) */
  arg1[0]=w6;
  res1[0]=w13;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #33: @14 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w14;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #34: @12 = mac(@13,@14,@12) */
  for (i=0, rr=w12; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w13+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #35: @13 = zeros(3x3) */
  casadi_clear(w13, 9);
  /* #36: @14 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w14;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #37: @15 = VecToso3(@6) */
  arg1[0]=w6;
  res1[0]=w15;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #38: @13 = mac(@14,@15,@13) */
  for (i=0, rr=w13; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w15+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #39: @12 = (@12+@13) */
  for (i=0, rr=w12, cs=w13; i<9; ++i) (*rr++) += (*cs++);
  /* #40: @12 = (@9*@12) */
  for (i=0, rr=w12, cs=w12; i<9; ++i) (*rr++)  = (w9*(*cs++));
  /* #41: @10 = (@10+@12) */
  for (i=0, rr=w10, cs=w12; i<9; ++i) (*rr++) += (*cs++);
  /* #42: @9 = (@5-@8) */
  w9  = (w5-w8);
  /* #43: @11 = sq(@3) */
  w11 = casadi_sq( w3 );
  /* #44: @9 = (@9/@11) */
  w9 /= w11;
  /* #45: @11 = 0 */
  w11 = 0.;
  /* #46: @16 = @1' */
  casadi_copy(w1, 3, w16);
  /* #47: @11 = mac(@16,@6,@11) */
  for (i=0, rr=(&w11); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #48: @9 = (@9*@11) */
  w9 *= w11;
  /* #49: @12 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w12;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #50: @12 = (@9*@12) */
  for (i=0, rr=w12, cs=w12; i<9; ++i) (*rr++)  = (w9*(*cs++));
  /* #51: @10 = (@10+@12) */
  for (i=0, rr=w10, cs=w12; i<9; ++i) (*rr++) += (*cs++);
  /* #52: @12 = zeros(3x3) */
  casadi_clear(w12, 9);
  /* #53: @9 = 3 */
  w9 = 3.;
  /* #54: @11 = 1 */
  w11 = 1.;
  /* #55: @11 = (@11-@5) */
  w11 -= w5;
  /* #56: @9 = (@9*@11) */
  w9 *= w11;
  /* #57: @11 = sq(@3) */
  w11 = casadi_sq( w3 );
  /* #58: @9 = (@9/@11) */
  w9 /= w11;
  /* #59: @11 = 2 */
  w11 = 2.;
  /* #60: @8 = (@8/@11) */
  w8 /= w11;
  /* #61: @9 = (@9-@8) */
  w9 -= w8;
  /* #62: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #63: @9 = (@9/@3) */
  w9 /= w3;
  /* #64: @3 = 0 */
  w3 = 0.;
  /* #65: @16 = @1' */
  casadi_copy(w1, 3, w16);
  /* #66: @3 = mac(@16,@6,@3) */
  for (i=0, rr=(&w3); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w16+j, tt=w6+i*3; k<3; ++k) *rr += ss[k*1]**tt++;
  /* #67: @9 = (@9*@3) */
  w9 *= w3;
  /* #68: @13 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w13;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #69: @14 = (@9*@13) */
  for (i=0, rr=w14, cs=w13; i<9; ++i) (*rr++)  = (w9*(*cs++));
  /* #70: @12 = mac(@14,@13,@12) */
  for (i=0, rr=w12; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w14+j, tt=w13+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #71: @10 = (@10-@12) */
  for (i=0, rr=w10, cs=w12; i<9; ++i) (*rr++) -= (*cs++);
  /* #72: @10 = (@4?@10:0) */
  for (i=0, rr=w10, cs=w10; i<9; ++i) (*rr++)  = (w4?cs[i]:0);
  /* #73: @7 = (@7+@10) */
  for (i=0, rr=w7, cs=w10; i<9; ++i) (*rr++) += (*cs++);
  /* #74: @17 = horzcat(@2, @7) */
  rr=w17;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<9; ++i) *rr++ = *cs++;
  /* #75: @18 = @17' */
  for (i=0, rr=w18, cs=w17; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #76: @2 = zeros(3x3) */
  casadi_clear(w2, 9);
  /* #77: @7 = dexp3(@1) */
  arg1[0]=w1;
  res1[0]=w7;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #78: @17 = horzcat(@2, @7) */
  rr=w17;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<9; ++i) *rr++ = *cs++;
  /* #79: @19 = @17' */
  for (i=0, rr=w19, cs=w17; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #80: @20 = horzcat(@18, @19) */
  rr=w20;
  for (i=0, cs=w18; i<18; ++i) *rr++ = *cs++;
  for (i=0, cs=w19; i<18; ++i) *rr++ = *cs++;
  /* #81: @21 = @20' */
  for (i=0, rr=w21, cs=w20; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #82: output[0][0] = @21 */
  casadi_copy(w21, 36, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int dexp6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dexp6_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dexp6_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dexp6_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dexp6_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dexp6_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dexp6_incref(void) {
}

CASADI_SYMBOL_EXPORT void dexp6_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dexp6_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int dexp6_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dexp6_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dexp6_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dexp6_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dexp6_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dexp6_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dexp6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 283;
  return 0;
}

CASADI_SYMBOL_EXPORT int dexp6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 283*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_dexp6(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[325];
  casadi_int *iw = 0;
  const casadi_real* arg[6] = {0};
  casadi_real* res[4] = {0};
  if (argc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"dexp6\" failed. Too many input arguments (%d, max 1)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"dexp6\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+42);
  --resc;
  res[0] = w+6;
  dexp6_incref();
  mem = dexp6_checkout();
  i = dexp6(arg, res, iw, w+42, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"dexp6\" failed.");
  dexp6_release(mem);
  dexp6_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[6];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_dexp6(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "dexp6")==0) {
    mex_dexp6(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'dexp6'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
