/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dlog3_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s1[15] = {3, 3, 0, 3, 6, 9, 0, 1, 2, 0, 1, 2, 0, 1, 2};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* VecToso3:(i0[3])->(o0[3x3]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, *w5=w+9, *w6=w+12, *w7=w+21;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @4 = horzcat(@0, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #6: @4 = @4' */
  /* #7: @0 = @1[2] */
  for (rr=(&w0), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #8: @2 = 0 */
  w2 = 0.;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (-@3) */
  w3 = (- w3 );
  /* #11: @5 = horzcat(@0, @2, @3) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @5 = @5' */
  /* #13: @0 = @1[1] */
  for (rr=(&w0), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @0 = (-@0) */
  w0 = (- w0 );
  /* #15: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @3 = 0 */
  w3 = 0.;
  /* #17: @1 = horzcat(@0, @2, @3) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #18: @1 = @1' */
  /* #19: @6 = horzcat(@4, @5, @1) */
  rr=w6;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #20: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

/* dlog3:(i0[3])->(o0[3x3]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+30, w1, w2, *w3=w+35, *w4=w+44, w5, *w6=w+54, w7, w8, *w9=w+65;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(3, w0, w0));
  /* #2: @2 = 2.22045e-16 */
  w2 = 2.2204460492503131e-16;
  /* #3: @2 = (@1<@2) */
  w2  = (w1<w2);
  /* #4: @3 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w3);
  /* #5: @3 = (@2?@3:0) */
  for (i=0, rr=w3, cs=w3; i<9; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #6: @2 = (!@2) */
  w2 = (! w2 );
  /* #7: @4 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w4);
  /* #8: @5 = 0.5 */
  w5 = 5.0000000000000000e-01;
  /* #9: @6 = VecToso3(@0) */
  arg1[0]=w0;
  res1[0]=w6;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #10: @6 = (@5*@6) */
  for (i=0, rr=w6, cs=w6; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #11: @4 = (@4-@6) */
  for (i=0, rr=w4, cs=w6; i<9; ++i) (*rr++) -= (*cs++);
  /* #12: @5 = 1 */
  w5 = 1.;
  /* #13: @7 = 2 */
  w7 = 2.;
  /* #14: @7 = (@1/@7) */
  w7  = (w1/w7);
  /* #15: @7 = sin(@7) */
  w7 = sin( w7 );
  /* #16: @8 = 2 */
  w8 = 2.;
  /* #17: @8 = (@1/@8) */
  w8  = (w1/w8);
  /* #18: @7 = (@7/@8) */
  w7 /= w8;
  /* #19: @8 = 2 */
  w8 = 2.;
  /* #20: @8 = (@1/@8) */
  w8  = (w1/w8);
  /* #21: @8 = cos(@8) */
  w8 = cos( w8 );
  /* #22: @8 = (@7*@8) */
  w8  = (w7*w8);
  /* #23: @7 = sq(@7) */
  w7 = casadi_sq( w7 );
  /* #24: @8 = (@8/@7) */
  w8 /= w7;
  /* #25: @5 = (@5-@8) */
  w5 -= w8;
  /* #26: @1 = sq(@1) */
  w1 = casadi_sq( w1 );
  /* #27: @5 = (@5/@1) */
  w5 /= w1;
  /* #28: @6 = zeros(3x3) */
  casadi_clear(w6, 9);
  /* #29: @9 = VecToso3(@0) */
  arg1[0]=w0;
  res1[0]=w9;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #30: @6 = mac(@9,@9,@6) */
  for (i=0, rr=w6; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w9+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #31: @6 = (@5*@6) */
  for (i=0, rr=w6, cs=w6; i<9; ++i) (*rr++)  = (w5*(*cs++));
  /* #32: @4 = (@4+@6) */
  for (i=0, rr=w4, cs=w6; i<9; ++i) (*rr++) += (*cs++);
  /* #33: @4 = (@2?@4:0) */
  for (i=0, rr=w4, cs=w4; i<9; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #34: @3 = (@3+@4) */
  for (i=0, rr=w3, cs=w4; i<9; ++i) (*rr++) += (*cs++);
  /* #35: output[0][0] = @3 */
  casadi_copy(w3, 9, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int dlog3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int dlog3_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int dlog3_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dlog3_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int dlog3_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void dlog3_release(int mem) {
}

CASADI_SYMBOL_EXPORT void dlog3_incref(void) {
}

CASADI_SYMBOL_EXPORT void dlog3_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int dlog3_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int dlog3_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real dlog3_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dlog3_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* dlog3_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dlog3_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* dlog3_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int dlog3_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 74;
  return 0;
}

CASADI_SYMBOL_EXPORT int dlog3_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 5*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 3*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 74*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_dlog3(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[86];
  casadi_int *iw = 0;
  const casadi_real* arg[5] = {0};
  casadi_real* res[3] = {0};
  if (argc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"dlog3\" failed. Too many input arguments (%d, max 1)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"dlog3\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+12);
  --resc;
  res[0] = w+3;
  dlog3_incref();
  mem = dlog3_checkout();
  i = dlog3(arg, res, iw, w+12, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"dlog3\" failed.");
  dlog3_release(mem);
  dlog3_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[6];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_dlog3(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "dlog3")==0) {
    mex_dlog3(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'dlog3'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
