/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FKinSpace_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s1[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s2[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c1[4] = {0., 0., 0., 1.};

/* VecToso3:(i0[3])->(o0[3x3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, *w5=w+9, *w6=w+12, *w7=w+21;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @4 = horzcat(@0, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #6: @4 = @4' */
  /* #7: @0 = @1[2] */
  for (rr=(&w0), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #8: @2 = 0 */
  w2 = 0.;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (-@3) */
  w3 = (- w3 );
  /* #11: @5 = horzcat(@0, @2, @3) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @5 = @5' */
  /* #13: @0 = @1[1] */
  for (rr=(&w0), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @0 = (-@0) */
  w0 = (- w0 );
  /* #15: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @3 = 0 */
  w3 = 0.;
  /* #17: @1 = horzcat(@0, @2, @3) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #18: @1 = @1' */
  /* #19: @6 = horzcat(@4, @5, @1) */
  rr=w6;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #20: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

/* VecTose3:(i0[6])->(o0[4x4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+30, *w1=w+36, *w2=w+39, *w3=w+48, *w4=w+60, *w5=w+72, *w6=w+76, *w7=w+92;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w0);
  /* #1: @1 = @0[3:6] */
  for (rr=w1, ss=w0+3; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #2: @2 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #3: @1 = @0[:3] */
  for (rr=w1, ss=w0+0; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #4: @3 = horzcat(@2, @1) */
  rr=w3;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #5: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #6: @5 = zeros(4x1) */
  casadi_clear(w5, 4);
  /* #7: @6 = horzcat(@4, @5) */
  rr=w6;
  for (i=0, cs=w4; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<4; ++i) *rr++ = *cs++;
  /* #8: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #9: output[0][0] = @7 */
  casadi_copy(w7, 16, res[0]);
  return 0;
}

/* so3ToVec:(i0[3x3])->(o0[3]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 9, w0);
  /* #1: @1 = @0[5] */
  for (rr=(&w1), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = @0[6] */
  for (rr=(&w1), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #5: @1 = @0[1] */
  for (rr=(&w1), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #6: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  return 0;
}

/* NearZero:(i0)->(o0) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(1, (&w0), (&w0)));
  /* #2: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #3: @1 = (@1<@0) */
  w1  = (w1<w0);
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* so3ToVec:(i0[3x3])->(o0[3]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 9, w0);
  /* #1: @1 = @0[5] */
  for (rr=(&w1), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = @0[6] */
  for (rr=(&w1), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #5: @1 = @0[1] */
  for (rr=(&w1), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #6: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  return 0;
}

/* NearZero:(i0)->(o0) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(1, (&w0), (&w0)));
  /* #2: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #3: @1 = (@1<@0) */
  w1  = (w1<w0);
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* AxisAng3:(i0[3])->(o0[3x3],o1) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+2, w1, w2, *w3=w+7;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(3, w0, w0));
  /* #2: @2 = NearZero(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w2);
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #3: @2 = (!@2) */
  w2 = (! w2 );
  /* #4: @0 = (@0/@1) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) /= w1;
  /* #5: @0 = (@2?@0:0) */
  for (i=0, rr=w0, cs=w0; i<3; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #6: @3 = repmat(@0, 3) */
  for (i=0;i<3;++i) {
    casadi_copy(w0, 3, w3+ i*3);
  }
  /* #7: output[0][0] = @3 */
  casadi_copy(w3, 9, res[0]);
  /* #8: output[1][0] = @1 */
  if (res[1]) res[1][0] = w1;
  return 0;
}

/* NearZero:(i0)->(o0) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(1, (&w0), (&w0)));
  /* #2: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #3: @1 = (@1<@0) */
  w1  = (w1<w0);
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* MatrixExp3:(i0[3x3])->(o0[3x3]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+16, *w1=w+25, w2, w3, *w4=w+30, *w5=w+39, w6, *w7=w+49, w8, *w9=w+59;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 9, w0);
  /* #1: @1 = so3ToVec(@0) */
  arg1[0]=w0;
  res1[0]=w1;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #2: {NULL, @2} = AxisAng3(@1) */
  arg1[0]=w1;
  res1[0]=0;
  res1[1]=(&w2);
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #3: @3 = NearZero(@2) */
  arg1[0]=(&w2);
  res1[0]=(&w3);
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #4: @4 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w4);
  /* #5: @4 = (@3?@4:0) */
  for (i=0, rr=w4, cs=w4; i<9; ++i) (*rr++)  = (w3?cs[i]:0);
  /* #6: @3 = (!@3) */
  w3 = (! w3 );
  /* #7: @5 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w5);
  /* #8: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #9: @6 = (@6/@2) */
  w6 /= w2;
  /* #10: @7 = (@6*@0) */
  for (i=0, rr=w7, cs=w0; i<9; ++i) (*rr++)  = (w6*(*cs++));
  /* #11: @5 = (@5+@7) */
  for (i=0, rr=w5, cs=w7; i<9; ++i) (*rr++) += (*cs++);
  /* #12: @7 = zeros(3x3) */
  casadi_clear(w7, 9);
  /* #13: @6 = 1 */
  w6 = 1.;
  /* #14: @8 = cos(@2) */
  w8 = cos( w2 );
  /* #15: @6 = (@6-@8) */
  w6 -= w8;
  /* #16: @6 = (@6/@2) */
  w6 /= w2;
  /* #17: @6 = (@6/@2) */
  w6 /= w2;
  /* #18: @9 = (@6*@0) */
  for (i=0, rr=w9, cs=w0; i<9; ++i) (*rr++)  = (w6*(*cs++));
  /* #19: @7 = mac(@9,@0,@7) */
  for (i=0, rr=w7; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #20: @5 = (@5+@7) */
  for (i=0, rr=w5, cs=w7; i<9; ++i) (*rr++) += (*cs++);
  /* #21: @5 = (@3?@5:0) */
  for (i=0, rr=w5, cs=w5; i<9; ++i) (*rr++)  = (w3?cs[i]:0);
  /* #22: @4 = (@4+@5) */
  for (i=0, rr=w4, cs=w5; i<9; ++i) (*rr++) += (*cs++);
  /* #23: output[0][0] = @4 */
  casadi_copy(w4, 9, res[0]);
  return 0;
}

/* NearZero:(i0)->(o0) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(1, (&w0), (&w0)));
  /* #2: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #3: @1 = (@1<@0) */
  w1  = (w1<w0);
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* AxisAng3:(i0[3])->(o0[3x3],o1) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+2, w1, w2, *w3=w+7;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(3, w0, w0));
  /* #2: @2 = NearZero(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w2);
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #3: @2 = (!@2) */
  w2 = (! w2 );
  /* #4: @0 = (@0/@1) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) /= w1;
  /* #5: @0 = (@2?@0:0) */
  for (i=0, rr=w0, cs=w0; i<3; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #6: @3 = repmat(@0, 3) */
  for (i=0;i<3;++i) {
    casadi_copy(w0, 3, w3+ i*3);
  }
  /* #7: output[0][0] = @3 */
  casadi_copy(w3, 9, res[0]);
  /* #8: output[1][0] = @1 */
  if (res[1]) res[1][0] = w1;
  return 0;
}

/* MatrixExp6:(i0[4x4])->(o0[4x4]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+68, *w1=w+84, *w2=w+93, w3, w4, *w5=w+98, *w6=w+101, *w7=w+113, *w8=w+125, *w9=w+129, *w10=w+145, *w11=w+161, w12, w13, *w14=w+172, *w15=w+181, *w16=w+190;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: @1 = @0[:12:4;:3] */
  for (rr=w1, ss=w0+0; ss!=w0+12; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #2: @2 = so3ToVec(@1) */
  arg1[0]=w1;
  res1[0]=w2;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #3: @3 = ||@2||_F */
  w3 = sqrt(casadi_dot(3, w2, w2));
  /* #4: @4 = NearZero(@3) */
  arg1[0]=(&w3);
  res1[0]=(&w4);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #5: @1 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w1);
  /* #6: @5 = @0[12:15] */
  for (rr=w5, ss=w0+12; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #7: @6 = horzcat(@1, @5) */
  rr=w6;
  for (i=0, cs=w1; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  /* #8: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #9: @8 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 4, w8);
  /* #10: @8 = @8' */
  /* #11: @9 = horzcat(@7, @8) */
  rr=w9;
  for (i=0, cs=w7; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<4; ++i) *rr++ = *cs++;
  /* #12: @10 = @9' */
  for (i=0, rr=w10, cs=w9; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #13: @10 = (@4?@10:0) */
  for (i=0, rr=w10, cs=w10; i<16; ++i) (*rr++)  = (w4?cs[i]:0);
  /* #14: @4 = (!@4) */
  w4 = (! w4 );
  /* #15: @1 = @0[:12:4;:3] */
  for (rr=w1, ss=w0+0; ss!=w0+12; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #16: @11 = MatrixExp3(@1) */
  arg1[0]=w1;
  res1[0]=w11;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #17: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #18: @1 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w1);
  /* #19: {NULL, @3} = AxisAng3(@2) */
  arg1[0]=w2;
  res1[0]=0;
  res1[1]=(&w3);
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #20: @1 = (@1*@3) */
  for (i=0, rr=w1; i<9; ++i) (*rr++) *= w3;
  /* #21: @12 = 1 */
  w12 = 1.;
  /* #22: @13 = cos(@3) */
  w13 = cos( w3 );
  /* #23: @12 = (@12-@13) */
  w12 -= w13;
  /* #24: @14 = @0[:12:4;:3] */
  for (rr=w14, ss=w0+0; ss!=w0+12; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #25: @14 = (@14/@3) */
  for (i=0, rr=w14; i<9; ++i) (*rr++) /= w3;
  /* #26: @15 = (@12*@14) */
  for (i=0, rr=w15, cs=w14; i<9; ++i) (*rr++)  = (w12*(*cs++));
  /* #27: @1 = (@1+@15) */
  for (i=0, rr=w1, cs=w15; i<9; ++i) (*rr++) += (*cs++);
  /* #28: @15 = zeros(3x3) */
  casadi_clear(w15, 9);
  /* #29: @12 = sin(@3) */
  w12 = sin( w3 );
  /* #30: @12 = (@3-@12) */
  w12  = (w3-w12);
  /* #31: @16 = (@12*@14) */
  for (i=0, rr=w16, cs=w14; i<9; ++i) (*rr++)  = (w12*(*cs++));
  /* #32: @15 = mac(@16,@14,@15) */
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #33: @1 = (@1+@15) */
  for (i=0, rr=w1, cs=w15; i<9; ++i) (*rr++) += (*cs++);
  /* #34: @2 = @0[12:15] */
  for (rr=w2, ss=w0+12; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #35: @5 = mac(@1,@2,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #36: @5 = (@5/@3) */
  for (i=0, rr=w5; i<3; ++i) (*rr++) /= w3;
  /* #37: @7 = horzcat(@11, @5) */
  rr=w7;
  for (i=0, cs=w11; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  /* #38: @6 = @7' */
  for (i=0, rr=w6, cs=w7; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #39: @8 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c1, 4, w8);
  /* #40: @8 = @8' */
  /* #41: @0 = horzcat(@6, @8) */
  rr=w0;
  for (i=0, cs=w6; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<4; ++i) *rr++ = *cs++;
  /* #42: @9 = @0' */
  for (i=0, rr=w9, cs=w0; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #43: @9 = (@4?@9:0) */
  for (i=0, rr=w9, cs=w9; i<16; ++i) (*rr++)  = (w4?cs[i]:0);
  /* #44: @10 = (@10+@9) */
  for (i=0, rr=w10, cs=w9; i<16; ++i) (*rr++) += (*cs++);
  /* #45: output[0][0] = @10 */
  casadi_copy(w10, 16, res[0]);
  return 0;
}

/* FKinSpace:(i0[4x4],i1[6x6],i2[6])->(o0[4x4]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+3;
  casadi_real *w0=w+199, *w1=w+215, *w2=w+251, *w3=w+257, w4, *w5=w+264, *w6=w+280, *w7=w+296, *w8=w+312, *w9=w+328, *w10=w+344, *w11=w+360, *w12=w+376, *w13=w+392, *w14=w+408, *w15=w+424, *w16=w+440;
  /* #0: @0 = zeros(4x4) */
  casadi_clear(w0, 16);
  /* #1: @1 = input[1][0] */
  casadi_copy(arg[1], 36, w1);
  /* #2: @2 = @1[:6] */
  for (rr=w2, ss=w1+0; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #3: @3 = input[2][0] */
  casadi_copy(arg[2], 6, w3);
  /* #4: @4 = @3[0] */
  for (rr=(&w4), ss=w3+0; ss!=w3+1; ss+=1) *rr++ = *ss;
  /* #5: @2 = (@2*@4) */
  for (i=0, rr=w2; i<6; ++i) (*rr++) *= w4;
  /* #6: @5 = VecTose3(@2) */
  arg1[0]=w2;
  res1[0]=w5;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #7: @6 = MatrixExp6(@5) */
  arg1[0]=w5;
  res1[0]=w6;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #8: @5 = zeros(4x4) */
  casadi_clear(w5, 16);
  /* #9: @2 = @1[6:12] */
  for (rr=w2, ss=w1+6; ss!=w1+12; ss+=1) *rr++ = *ss;
  /* #10: @4 = @3[1] */
  for (rr=(&w4), ss=w3+1; ss!=w3+2; ss+=1) *rr++ = *ss;
  /* #11: @2 = (@2*@4) */
  for (i=0, rr=w2; i<6; ++i) (*rr++) *= w4;
  /* #12: @7 = VecTose3(@2) */
  arg1[0]=w2;
  res1[0]=w7;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #13: @8 = MatrixExp6(@7) */
  arg1[0]=w7;
  res1[0]=w8;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #14: @7 = zeros(4x4) */
  casadi_clear(w7, 16);
  /* #15: @2 = @1[12:18] */
  for (rr=w2, ss=w1+12; ss!=w1+18; ss+=1) *rr++ = *ss;
  /* #16: @4 = @3[2] */
  for (rr=(&w4), ss=w3+2; ss!=w3+3; ss+=1) *rr++ = *ss;
  /* #17: @2 = (@2*@4) */
  for (i=0, rr=w2; i<6; ++i) (*rr++) *= w4;
  /* #18: @9 = VecTose3(@2) */
  arg1[0]=w2;
  res1[0]=w9;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #19: @10 = MatrixExp6(@9) */
  arg1[0]=w9;
  res1[0]=w10;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #20: @9 = zeros(4x4) */
  casadi_clear(w9, 16);
  /* #21: @2 = @1[18:24] */
  for (rr=w2, ss=w1+18; ss!=w1+24; ss+=1) *rr++ = *ss;
  /* #22: @4 = @3[3] */
  for (rr=(&w4), ss=w3+3; ss!=w3+4; ss+=1) *rr++ = *ss;
  /* #23: @2 = (@2*@4) */
  for (i=0, rr=w2; i<6; ++i) (*rr++) *= w4;
  /* #24: @11 = VecTose3(@2) */
  arg1[0]=w2;
  res1[0]=w11;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #25: @12 = MatrixExp6(@11) */
  arg1[0]=w11;
  res1[0]=w12;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #26: @11 = zeros(4x4) */
  casadi_clear(w11, 16);
  /* #27: @2 = @1[24:30] */
  for (rr=w2, ss=w1+24; ss!=w1+30; ss+=1) *rr++ = *ss;
  /* #28: @4 = @3[4] */
  for (rr=(&w4), ss=w3+4; ss!=w3+5; ss+=1) *rr++ = *ss;
  /* #29: @2 = (@2*@4) */
  for (i=0, rr=w2; i<6; ++i) (*rr++) *= w4;
  /* #30: @13 = VecTose3(@2) */
  arg1[0]=w2;
  res1[0]=w13;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #31: @14 = MatrixExp6(@13) */
  arg1[0]=w13;
  res1[0]=w14;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #32: @13 = zeros(4x4) */
  casadi_clear(w13, 16);
  /* #33: @2 = @1[30:36] */
  for (rr=w2, ss=w1+30; ss!=w1+36; ss+=1) *rr++ = *ss;
  /* #34: @4 = @3[5] */
  for (rr=(&w4), ss=w3+5; ss!=w3+6; ss+=1) *rr++ = *ss;
  /* #35: @2 = (@2*@4) */
  for (i=0, rr=w2; i<6; ++i) (*rr++) *= w4;
  /* #36: @15 = VecTose3(@2) */
  arg1[0]=w2;
  res1[0]=w15;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #37: @16 = MatrixExp6(@15) */
  arg1[0]=w15;
  res1[0]=w16;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #38: @15 = input[0][0] */
  casadi_copy(arg[0], 16, w15);
  /* #39: @13 = mac(@16,@15,@13) */
  for (i=0, rr=w13; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w16+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #40: @11 = mac(@14,@13,@11) */
  for (i=0, rr=w11; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w14+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #41: @9 = mac(@12,@11,@9) */
  for (i=0, rr=w9; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w12+j, tt=w11+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #42: @7 = mac(@10,@9,@7) */
  for (i=0, rr=w7; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w10+j, tt=w9+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #43: @5 = mac(@8,@7,@5) */
  for (i=0, rr=w5; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w8+j, tt=w7+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #44: @0 = mac(@6,@5,@0) */
  for (i=0, rr=w0; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w6+j, tt=w5+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #45: output[0][0] = @0 */
  casadi_copy(w0, 16, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int FKinSpace(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int FKinSpace_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int FKinSpace_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FKinSpace_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int FKinSpace_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void FKinSpace_release(int mem) {
}

CASADI_SYMBOL_EXPORT void FKinSpace_incref(void) {
}

CASADI_SYMBOL_EXPORT void FKinSpace_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int FKinSpace_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int FKinSpace_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real FKinSpace_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FKinSpace_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* FKinSpace_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FKinSpace_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* FKinSpace_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int FKinSpace_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9;
  if (sz_res) *sz_res = 7;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 456;
  return 0;
}

CASADI_SYMBOL_EXPORT int FKinSpace_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 9*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 7*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 456*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_FKinSpace(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[530];
  casadi_int *iw = 0;
  const casadi_real* arg[9] = {0};
  casadi_real* res[7] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"FKinSpace\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"FKinSpace\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+74);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+16, casadi_s1, w+74);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+52, casadi_s2, w+74);
  --resc;
  res[0] = w+58;
  FKinSpace_incref();
  mem = FKinSpace_checkout();
  i = FKinSpace(arg, res, iw, w+74, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"FKinSpace\" failed.");
  FKinSpace_release(mem);
  FKinSpace_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s0, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[10];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_FKinSpace(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "FKinSpace")==0) {
    mex_FKinSpace(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'FKinSpace'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
