/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) JointTrajectoryTime_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[11] = {7, 1, 0, 7, 0, 1, 2, 3, 4, 5, 6};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};

/* JointTrajectoryTime:(i0[7],i1[7],i2,i3,i4)->(o0[7],o1[7],o2[7]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real *rr;
  const casadi_real *cr, *cs;
  casadi_real *w0=w+0, w1, w2, w3, w4, w5, w6, w7, w8, w9, *w10=w+16, *w11=w+23;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 7, w0);
  /* #1: @1 = 3 */
  w1 = 3.;
  /* #2: @2 = input[3][0] */
  w2 = arg[3] ? arg[3][0] : 0;
  /* #3: @1 = (@1==@2) */
  w1  = (w1==w2);
  /* #4: @2 = 3 */
  w2 = 3.;
  /* #5: @3 = input[2][0] */
  w3 = arg[2] ? arg[2][0] : 0;
  /* #6: @4 = input[4][0] */
  w4 = arg[4] ? arg[4][0] : 0;
  /* #7: @5 = (@3<@4) */
  w5  = (w3<w4);
  /* #8: @6 = (@5?@3:0) */
  w6  = (w5?w3:0);
  /* #9: @5 = (!@5) */
  w5 = (! w5 );
  /* #10: @5 = (@5?@4:0) */
  w5  = (w5?w4:0);
  /* #11: @6 = (@6+@5) */
  w6 += w5;
  /* #12: @5 = sq(@6) */
  w5 = casadi_sq( w6 );
  /* #13: @4 = sq(@3) */
  w4 = casadi_sq( w3 );
  /* #14: @5 = (@5/@4) */
  w5 /= w4;
  /* #15: @2 = (@2*@5) */
  w2 *= w5;
  /* #16: @5 = 3 */
  w5 = 3.;
  /* #17: @5 = pow(@6,@5) */
  w5  = pow(w6,w5);
  /* #18: @4 = 3 */
  w4 = 3.;
  /* #19: @4 = pow(@3,@4) */
  w4  = pow(w3,w4);
  /* #20: @5 = (@5/@4) */
  w5 /= w4;
  /* #21: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #22: @2 = (@2-@5) */
  w2 -= w5;
  /* #23: @2 = (@1?@2:0) */
  w2  = (w1?w2:0);
  /* #24: @5 = (!@1) */
  w5 = (! w1 );
  /* #25: @4 = 10 */
  w4 = 10.;
  /* #26: @7 = (@6/@3) */
  w7  = (w6/w3);
  /* #27: @8 = 3 */
  w8 = 3.;
  /* #28: @8 = pow(@7,@8) */
  w8  = pow(w7,w8);
  /* #29: @4 = (@4*@8) */
  w4 *= w8;
  /* #30: @8 = 15 */
  w8 = 15.;
  /* #31: @9 = 4 */
  w9 = 4.;
  /* #32: @9 = pow(@7,@9) */
  w9  = pow(w7,w9);
  /* #33: @8 = (@8*@9) */
  w8 *= w9;
  /* #34: @4 = (@4-@8) */
  w4 -= w8;
  /* #35: @8 = 6 */
  w8 = 6.;
  /* #36: @9 = 5 */
  w9 = 5.;
  /* #37: @9 = pow(@7,@9) */
  w9  = pow(w7,w9);
  /* #38: @8 = (@8*@9) */
  w8 *= w9;
  /* #39: @4 = (@4+@8) */
  w4 += w8;
  /* #40: @5 = (@5?@4:0) */
  w5  = (w5?w4:0);
  /* #41: @2 = (@2+@5) */
  w2 += w5;
  /* #42: @10 = input[1][0] */
  casadi_copy(arg[1], 7, w10);
  /* #43: @11 = (@10-@0) */
  for (i=0, rr=w11, cr=w10, cs=w0; i<7; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #44: @11 = (@2*@11) */
  for (i=0, rr=w11, cs=w11; i<7; ++i) (*rr++)  = (w2*(*cs++));
  /* #45: @11 = (@0+@11) */
  for (i=0, rr=w11, cr=w0, cs=w11; i<7; ++i) (*rr++)  = ((*cr++)+(*cs++));
  /* #46: output[0][0] = @11 */
  casadi_copy(w11, 7, res[0]);
  /* #47: @2 = 6 */
  w2 = 6.;
  /* #48: @5 = sq(@3) */
  w5 = casadi_sq( w3 );
  /* #49: @5 = (@6/@5) */
  w5  = (w6/w5);
  /* #50: @2 = (@2*@5) */
  w2 *= w5;
  /* #51: @5 = 6 */
  w5 = 6.;
  /* #52: @4 = sq(@6) */
  w4 = casadi_sq( w6 );
  /* #53: @8 = 3 */
  w8 = 3.;
  /* #54: @8 = pow(@3,@8) */
  w8  = pow(w3,w8);
  /* #55: @4 = (@4/@8) */
  w4 /= w8;
  /* #56: @5 = (@5*@4) */
  w5 *= w4;
  /* #57: @2 = (@2-@5) */
  w2 -= w5;
  /* #58: @2 = (@1?@2:0) */
  w2  = (w1?w2:0);
  /* #59: @5 = (!@1) */
  w5 = (! w1 );
  /* #60: @4 = 30 */
  w4 = 30.;
  /* #61: @8 = sq(@7) */
  w8 = casadi_sq( w7 );
  /* #62: @4 = (@4*@8) */
  w4 *= w8;
  /* #63: @8 = 60 */
  w8 = 60.;
  /* #64: @9 = 3 */
  w9 = 3.;
  /* #65: @9 = pow(@7,@9) */
  w9  = pow(w7,w9);
  /* #66: @8 = (@8*@9) */
  w8 *= w9;
  /* #67: @4 = (@4-@8) */
  w4 -= w8;
  /* #68: @8 = 30 */
  w8 = 30.;
  /* #69: @9 = 4 */
  w9 = 4.;
  /* #70: @9 = pow(@7,@9) */
  w9  = pow(w7,w9);
  /* #71: @8 = (@8*@9) */
  w8 *= w9;
  /* #72: @4 = (@4+@8) */
  w4 += w8;
  /* #73: @4 = (@4/@3) */
  w4 /= w3;
  /* #74: @5 = (@5?@4:0) */
  w5  = (w5?w4:0);
  /* #75: @2 = (@2+@5) */
  w2 += w5;
  /* #76: @11 = (@10-@0) */
  for (i=0, rr=w11, cr=w10, cs=w0; i<7; ++i) (*rr++)  = ((*cr++)-(*cs++));
  /* #77: @11 = (@2*@11) */
  for (i=0, rr=w11, cs=w11; i<7; ++i) (*rr++)  = (w2*(*cs++));
  /* #78: output[1][0] = @11 */
  casadi_copy(w11, 7, res[1]);
  /* #79: @2 = 6 */
  w2 = 6.;
  /* #80: @5 = sq(@3) */
  w5 = casadi_sq( w3 );
  /* #81: @2 = (@2/@5) */
  w2 /= w5;
  /* #82: @5 = 12 */
  w5 = 12.;
  /* #83: @4 = 3 */
  w4 = 3.;
  /* #84: @4 = pow(@3,@4) */
  w4  = pow(w3,w4);
  /* #85: @6 = (@6/@4) */
  w6 /= w4;
  /* #86: @5 = (@5*@6) */
  w5 *= w6;
  /* #87: @2 = (@2-@5) */
  w2 -= w5;
  /* #88: @2 = (@1?@2:0) */
  w2  = (w1?w2:0);
  /* #89: @1 = (!@1) */
  w1 = (! w1 );
  /* #90: @5 = 60 */
  w5 = 60.;
  /* #91: @5 = (@5*@7) */
  w5 *= w7;
  /* #92: @6 = 180 */
  w6 = 180.;
  /* #93: @4 = sq(@7) */
  w4 = casadi_sq( w7 );
  /* #94: @6 = (@6*@4) */
  w6 *= w4;
  /* #95: @5 = (@5-@6) */
  w5 -= w6;
  /* #96: @6 = 120 */
  w6 = 120.;
  /* #97: @4 = 3 */
  w4 = 3.;
  /* #98: @7 = pow(@7,@4) */
  w7  = pow(w7,w4);
  /* #99: @6 = (@6*@7) */
  w6 *= w7;
  /* #100: @5 = (@5+@6) */
  w5 += w6;
  /* #101: @3 = sq(@3) */
  w3 = casadi_sq( w3 );
  /* #102: @5 = (@5/@3) */
  w5 /= w3;
  /* #103: @1 = (@1?@5:0) */
  w1  = (w1?w5:0);
  /* #104: @2 = (@2+@1) */
  w2 += w1;
  /* #105: @10 = (@10-@0) */
  for (i=0, rr=w10, cs=w0; i<7; ++i) (*rr++) -= (*cs++);
  /* #106: @10 = (@2*@10) */
  for (i=0, rr=w10, cs=w10; i<7; ++i) (*rr++)  = (w2*(*cs++));
  /* #107: output[2][0] = @10 */
  casadi_copy(w10, 7, res[2]);
  return 0;
}

CASADI_SYMBOL_EXPORT int JointTrajectoryTime(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int JointTrajectoryTime_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int JointTrajectoryTime_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void JointTrajectoryTime_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int JointTrajectoryTime_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void JointTrajectoryTime_release(int mem) {
}

CASADI_SYMBOL_EXPORT void JointTrajectoryTime_incref(void) {
}

CASADI_SYMBOL_EXPORT void JointTrajectoryTime_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int JointTrajectoryTime_n_in(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_int JointTrajectoryTime_n_out(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_real JointTrajectoryTime_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JointTrajectoryTime_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* JointTrajectoryTime_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* JointTrajectoryTime_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* JointTrajectoryTime_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int JointTrajectoryTime_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 30;
  return 0;
}

CASADI_SYMBOL_EXPORT int JointTrajectoryTime_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 30*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_JointTrajectoryTime(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[68];
  casadi_int *iw = 0;
  const casadi_real* arg[7] = {0};
  casadi_real* res[4] = {0};
  if (argc>5) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"JointTrajectoryTime\" failed. Too many input arguments (%d, max 5)", argc);
  if (resc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"JointTrajectoryTime\" failed. Too many output arguments (%d, max 3)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+38);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+7, casadi_s0, w+38);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+14, casadi_s1, w+38);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+15, casadi_s1, w+38);
  if (--argc>=0) arg[4] = casadi_from_mex(argv[4], w+16, casadi_s1, w+38);
  --resc;
  res[0] = w+17;
  if (--resc>=0) res[1] = w+24;
  if (--resc>=0) res[2] = w+31;
  JointTrajectoryTime_incref();
  mem = JointTrajectoryTime_checkout();
  i = JointTrajectoryTime(arg, res, iw, w+38, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"JointTrajectoryTime\" failed.");
  JointTrajectoryTime_release(mem);
  JointTrajectoryTime_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s0, res[0]);
  if (res[1]) resv[1] = casadi_to_mex(casadi_s0, res[1]);
  if (res[2]) resv[2] = casadi_to_mex(casadi_s0, res[2]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[20];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_JointTrajectoryTime(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "JointTrajectoryTime")==0) {
    mex_JointTrajectoryTime(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'JointTrajectoryTime'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
