/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) log6_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[23] = {4, 4, 0, 4, 8, 12, 16, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3};
static const casadi_int casadi_s1[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

static const casadi_real casadi_c0[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};

/* TransToRp:(i0[4x4])->(o0[3x3],o1[3]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss, *tt;
  casadi_real *w0=w+0, *w1=w+16, *w2=w+25;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: @1 = @0[:12:4;:3] */
  for (rr=w1, ss=w0+0; ss!=w0+12; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 9, res[0]);
  /* #3: @2 = @0[12:15] */
  for (rr=w2, ss=w0+12; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #4: output[1][0] = @2 */
  casadi_copy(w2, 3, res[1]);
  return 0;
}

/* NearZero:(i0)->(o0) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(1, (&w0), (&w0)));
  /* #2: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #3: @1 = (@1<@0) */
  w1  = (w1<w0);
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* NearZero:(i0)->(o0) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(1, (&w0), (&w0)));
  /* #2: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #3: @1 = (@1<@0) */
  w1  = (w1<w0);
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* VecToso3:(i0[3])->(o0[3x3]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, *w5=w+9, *w6=w+12, *w7=w+21;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @4 = horzcat(@0, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #6: @4 = @4' */
  /* #7: @0 = @1[2] */
  for (rr=(&w0), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #8: @2 = 0 */
  w2 = 0.;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (-@3) */
  w3 = (- w3 );
  /* #11: @5 = horzcat(@0, @2, @3) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @5 = @5' */
  /* #13: @0 = @1[1] */
  for (rr=(&w0), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @0 = (-@0) */
  w0 = (- w0 );
  /* #15: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @3 = 0 */
  w3 = 0.;
  /* #17: @1 = horzcat(@0, @2, @3) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #18: @1 = @1' */
  /* #19: @6 = horzcat(@4, @5, @1) */
  rr=w6;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #20: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

/* MatrixLog3:(i0[3x3])->(o0[3x3]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real w0, *w1=w+31, w2, w3, w4, w5, w6, w7, w8, w9, *w10=w+48, *w11=w+51, *w12=w+54, *w13=w+57, *w14=w+66;
  /* #0: @0 = 1 */
  w0 = 1.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 9, w1);
  /* #2: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @3 = @1[4] */
  for (rr=(&w3), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #4: @2 = (@2+@3) */
  w2 += w3;
  /* #5: @3 = @1[8] */
  for (rr=(&w3), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #6: @2 = (@2+@3) */
  w2 += w3;
  /* #7: @3 = 1 */
  w3 = 1.;
  /* #8: @2 = (@2-@3) */
  w2 -= w3;
  /* #9: @3 = 2 */
  w3 = 2.;
  /* #10: @2 = (@2/@3) */
  w2 /= w3;
  /* #11: @0 = (@0<=@2) */
  w0  = (w0<=w2);
  /* #12: @0 = (!@0) */
  w0 = (! w0 );
  /* #13: @3 = -1 */
  w3 = -1.;
  /* #14: @3 = (@2<=@3) */
  w3  = (w2<=w3);
  /* #15: @4 = 3.14159 */
  w4 = 3.1415926535897931e+00;
  /* #16: @5 = 1 */
  w5 = 1.;
  /* #17: @6 = @1[8] */
  for (rr=(&w6), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #18: @5 = (@5+@6) */
  w5 += w6;
  /* #19: @6 = NearZero(@5) */
  arg1[0]=(&w5);
  res1[0]=(&w6);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #20: @6 = (!@6) */
  w6 = (! w6 );
  /* #21: @5 = @1[6] */
  for (rr=(&w5), ss=w1+6; ss!=w1+7; ss+=1) *rr++ = *ss;
  /* #22: @7 = @1[7] */
  for (rr=(&w7), ss=w1+7; ss!=w1+8; ss+=1) *rr++ = *ss;
  /* #23: @8 = 1 */
  w8 = 1.;
  /* #24: @9 = @1[8] */
  for (rr=(&w9), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #25: @8 = (@8+@9) */
  w8 += w9;
  /* #26: @10 = vertcat(@5, @7, @8) */
  rr=w10;
  *rr++ = w5;
  *rr++ = w7;
  *rr++ = w8;
  /* #27: @5 = 1 */
  w5 = 1.;
  /* #28: @7 = @1[8] */
  for (rr=(&w7), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #29: @5 = (@5+@7) */
  w5 += w7;
  /* #30: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #31: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #32: @10 = (@10/@5) */
  for (i=0, rr=w10; i<3; ++i) (*rr++) /= w5;
  /* #33: @10 = (@6?@10:0) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) (*rr++)  = (w6?cs[i]:0);
  /* #34: @6 = (!@6) */
  w6 = (! w6 );
  /* #35: @5 = 1 */
  w5 = 1.;
  /* #36: @7 = @1[4] */
  for (rr=(&w7), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #37: @5 = (@5+@7) */
  w5 += w7;
  /* #38: @7 = NearZero(@5) */
  arg1[0]=(&w5);
  res1[0]=(&w7);
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #39: @7 = (!@7) */
  w7 = (! w7 );
  /* #40: @5 = @1[3] */
  for (rr=(&w5), ss=w1+3; ss!=w1+4; ss+=1) *rr++ = *ss;
  /* #41: @8 = 1 */
  w8 = 1.;
  /* #42: @9 = @1[4] */
  for (rr=(&w9), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #43: @8 = (@8+@9) */
  w8 += w9;
  /* #44: @9 = @1[5] */
  for (rr=(&w9), ss=w1+5; ss!=w1+6; ss+=1) *rr++ = *ss;
  /* #45: @11 = vertcat(@5, @8, @9) */
  rr=w11;
  *rr++ = w5;
  *rr++ = w8;
  *rr++ = w9;
  /* #46: @5 = 1 */
  w5 = 1.;
  /* #47: @8 = @1[4] */
  for (rr=(&w8), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #48: @5 = (@5+@8) */
  w5 += w8;
  /* #49: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #50: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #51: @11 = (@11/@5) */
  for (i=0, rr=w11; i<3; ++i) (*rr++) /= w5;
  /* #52: @11 = (@7?@11:0) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) (*rr++)  = (w7?cs[i]:0);
  /* #53: @7 = (!@7) */
  w7 = (! w7 );
  /* #54: @5 = 1 */
  w5 = 1.;
  /* #55: @8 = @1[0] */
  for (rr=(&w8), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #56: @5 = (@5+@8) */
  w5 += w8;
  /* #57: @8 = @1[1] */
  for (rr=(&w8), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #58: @9 = @1[2] */
  for (rr=(&w9), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #59: @12 = vertcat(@5, @8, @9) */
  rr=w12;
  *rr++ = w5;
  *rr++ = w8;
  *rr++ = w9;
  /* #60: @5 = 1 */
  w5 = 1.;
  /* #61: @8 = @1[0] */
  for (rr=(&w8), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #62: @5 = (@5+@8) */
  w5 += w8;
  /* #63: @5 = (2.*@5) */
  w5 = (2.* w5 );
  /* #64: @5 = sqrt(@5) */
  w5 = sqrt( w5 );
  /* #65: @12 = (@12/@5) */
  for (i=0, rr=w12; i<3; ++i) (*rr++) /= w5;
  /* #66: @12 = (@7?@12:0) */
  for (i=0, rr=w12, cs=w12; i<3; ++i) (*rr++)  = (w7?cs[i]:0);
  /* #67: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<3; ++i) (*rr++) += (*cs++);
  /* #68: @11 = (@6?@11:0) */
  for (i=0, rr=w11, cs=w11; i<3; ++i) (*rr++)  = (w6?cs[i]:0);
  /* #69: @10 = (@10+@11) */
  for (i=0, rr=w10, cs=w11; i<3; ++i) (*rr++) += (*cs++);
  /* #70: @10 = (@4*@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) (*rr++)  = (w4*(*cs++));
  /* #71: @13 = VecToso3(@10) */
  arg1[0]=w10;
  res1[0]=w13;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #72: @13 = (@3?@13:0) */
  for (i=0, rr=w13, cs=w13; i<9; ++i) (*rr++)  = (w3?cs[i]:0);
  /* #73: @3 = (!@3) */
  w3 = (! w3 );
  /* #74: @2 = acos(@2) */
  w2 = acos( w2 );
  /* #75: @4 = sin(@2) */
  w4 = sin( w2 );
  /* #76: @4 = (2.*@4) */
  w4 = (2.* w4 );
  /* #77: @2 = (@2/@4) */
  w2 /= w4;
  /* #78: @14 = @1' */
  for (i=0, rr=w14, cs=w1; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #79: @1 = (@1-@14) */
  for (i=0, rr=w1, cs=w14; i<9; ++i) (*rr++) -= (*cs++);
  /* #80: @1 = (@2*@1) */
  for (i=0, rr=w1, cs=w1; i<9; ++i) (*rr++)  = (w2*(*cs++));
  /* #81: @1 = (@3?@1:0) */
  for (i=0, rr=w1, cs=w1; i<9; ++i) (*rr++)  = (w3?cs[i]:0);
  /* #82: @13 = (@13+@1) */
  for (i=0, rr=w13, cs=w1; i<9; ++i) (*rr++) += (*cs++);
  /* #83: @13 = (@0?@13:0) */
  for (i=0, rr=w13, cs=w13; i<9; ++i) (*rr++)  = (w0?cs[i]:0);
  /* #84: output[0][0] = @13 */
  casadi_copy(w13, 9, res[0]);
  return 0;
}

/* MatrixLog6:(i0[4x4])->(o0[4x4]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+1, *cr, *cs;
  casadi_real *w0=w+75, *w1=w+91, *w2=w+100, w3, w4, *w5=w+105, *w6=w+114, *w7=w+117, *w8=w+129, *w9=w+141, *w10=w+145, w11, *w12=w+162, w13, w14, *w15=w+173;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: {@1, @2} = TransToRp(@0) */
  arg1[0]=w0;
  res1[0]=w1;
  res1[1]=w2;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #2: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #3: @4 = @1[4] */
  for (rr=(&w4), ss=w1+4; ss!=w1+5; ss+=1) *rr++ = *ss;
  /* #4: @3 = (@3+@4) */
  w3 += w4;
  /* #5: @4 = @1[8] */
  for (rr=(&w4), ss=w1+8; ss!=w1+9; ss+=1) *rr++ = *ss;
  /* #6: @3 = (@3+@4) */
  w3 += w4;
  /* #7: @4 = 1 */
  w4 = 1.;
  /* #8: @3 = (@3-@4) */
  w3 -= w4;
  /* #9: @4 = 2 */
  w4 = 2.;
  /* #10: @3 = (@3/@4) */
  w3 /= w4;
  /* #11: @3 = acos(@3) */
  w3 = acos( w3 );
  /* #12: @4 = NearZero(@3) */
  arg1[0]=(&w3);
  res1[0]=(&w4);
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #13: @5 = zeros(3x3) */
  casadi_clear(w5, 9);
  /* #14: @6 = @0[12:15] */
  for (rr=w6, ss=w0+12; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #15: @7 = horzcat(@5, @6) */
  rr=w7;
  for (i=0, cs=w5; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  /* #16: @8 = @7' */
  for (i=0, rr=w8, cs=w7; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #17: @9 = zeros(4x1) */
  casadi_clear(w9, 4);
  /* #18: @0 = horzcat(@8, @9) */
  rr=w0;
  for (i=0, cs=w8; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  /* #19: @10 = @0' */
  for (i=0, rr=w10, cs=w0; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #20: @10 = (@4?@10:0) */
  for (i=0, rr=w10, cs=w10; i<16; ++i) (*rr++)  = (w4?cs[i]:0);
  /* #21: @4 = (!@4) */
  w4 = (! w4 );
  /* #22: @5 = MatrixLog3(@1) */
  arg1[0]=w1;
  res1[0]=w5;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #23: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #24: @1 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c0, 9, w1);
  /* #25: @11 = 2 */
  w11 = 2.;
  /* #26: @12 = (@5/@11) */
  for (i=0, rr=w12, cr=w5; i<9; ++i) (*rr++)  = ((*cr++)/w11);
  /* #27: @1 = (@1-@12) */
  for (i=0, rr=w1, cs=w12; i<9; ++i) (*rr++) -= (*cs++);
  /* #28: @11 = (1./@3) */
  w11 = (1./ w3 );
  /* #29: @13 = 2 */
  w13 = 2.;
  /* #30: @13 = (@3/@13) */
  w13  = (w3/w13);
  /* #31: @13 = tan(@13) */
  w13 = tan( w13 );
  /* #32: @13 = (1./@13) */
  w13 = (1./ w13 );
  /* #33: @14 = 2 */
  w14 = 2.;
  /* #34: @13 = (@13/@14) */
  w13 /= w14;
  /* #35: @11 = (@11-@13) */
  w11 -= w13;
  /* #36: @12 = zeros(3x3) */
  casadi_clear(w12, 9);
  /* #37: @12 = mac(@5,@5,@12) */
  for (i=0, rr=w12; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w5+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #38: @12 = (@11*@12) */
  for (i=0, rr=w12, cs=w12; i<9; ++i) (*rr++)  = (w11*(*cs++));
  /* #39: @12 = (@12/@3) */
  for (i=0, rr=w12; i<9; ++i) (*rr++) /= w3;
  /* #40: @1 = (@1+@12) */
  for (i=0, rr=w1, cs=w12; i<9; ++i) (*rr++) += (*cs++);
  /* #41: @6 = mac(@1,@2,@6) */
  for (i=0, rr=w6; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #42: @8 = horzcat(@5, @6) */
  rr=w8;
  for (i=0, cs=w5; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<3; ++i) *rr++ = *cs++;
  /* #43: @7 = @8' */
  for (i=0, rr=w7, cs=w8; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #44: @9 = zeros(4x1) */
  casadi_clear(w9, 4);
  /* #45: @0 = horzcat(@7, @9) */
  rr=w0;
  for (i=0, cs=w7; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w9; i<4; ++i) *rr++ = *cs++;
  /* #46: @15 = @0' */
  for (i=0, rr=w15, cs=w0; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #47: @15 = (@4?@15:0) */
  for (i=0, rr=w15, cs=w15; i<16; ++i) (*rr++)  = (w4?cs[i]:0);
  /* #48: @10 = (@10+@15) */
  for (i=0, rr=w10, cs=w15; i<16; ++i) (*rr++) += (*cs++);
  /* #49: output[0][0] = @10 */
  casadi_copy(w10, 16, res[0]);
  return 0;
}

/* se3ToVec:(i0[4x4])->(o0[6]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, *w1=w+16, w2;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: @1 = @0[12:15] */
  for (rr=w1, ss=w0+12; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 3, res[0]);
  /* #3: @2 = @0[6] */
  for (rr=(&w2), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #4: output[0][1] = @2 */
  if (res[0]) res[0][3] = w2;
  /* #5: @2 = @0[8] */
  for (rr=(&w2), ss=w0+8; ss!=w0+9; ss+=1) *rr++ = *ss;
  /* #6: output[0][2] = @2 */
  if (res[0]) res[0][4] = w2;
  /* #7: @2 = @0[1] */
  for (rr=(&w2), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #8: output[0][3] = @2 */
  if (res[0]) res[0][5] = w2;
  return 0;
}

/* log6:(i0[4x4])->(o0[6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1;
  const casadi_real **arg1=arg+1;
  casadi_real *w0=w+189, *w1=w+205, *w2=w+221;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: @1 = MatrixLog6(@0) */
  arg1[0]=w0;
  res1[0]=w1;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #2: @2 = se3ToVec(@1) */
  arg1[0]=w1;
  res1[0]=w2;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #3: output[0][0] = @2 */
  casadi_copy(w2, 6, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int log6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int log6_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int log6_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void log6_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int log6_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void log6_release(int mem) {
}

CASADI_SYMBOL_EXPORT void log6_incref(void) {
}

CASADI_SYMBOL_EXPORT void log6_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int log6_n_in(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_int log6_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real log6_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* log6_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* log6_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* log6_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* log6_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int log6_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 227;
  return 0;
}

CASADI_SYMBOL_EXPORT int log6_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 227*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_log6(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[249];
  casadi_int *iw = 0;
  const casadi_real* arg[7] = {0};
  casadi_real* res[5] = {0};
  if (argc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"log6\" failed. Too many input arguments (%d, max 1)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"log6\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+22);
  --resc;
  res[0] = w+16;
  log6_incref();
  mem = log6_checkout();
  i = log6(arg, res, iw, w+22, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"log6\" failed.");
  log6_release(mem);
  log6_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[5];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_log6(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "log6")==0) {
    mex_log6(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'log6'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
