/* This file was automatically generated by CasADi 3.6.7.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) MassMatrix_ ## ID
#endif

#include <math.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_c1 CASADI_PREFIX(c1)
#define casadi_c2 CASADI_PREFIX(c2)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_dot CASADI_PREFIX(dot)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f10 CASADI_PREFIX(f10)
#define casadi_f11 CASADI_PREFIX(f11)
#define casadi_f12 CASADI_PREFIX(f12)
#define casadi_f13 CASADI_PREFIX(f13)
#define casadi_f14 CASADI_PREFIX(f14)
#define casadi_f15 CASADI_PREFIX(f15)
#define casadi_f16 CASADI_PREFIX(f16)
#define casadi_f17 CASADI_PREFIX(f17)
#define casadi_f18 CASADI_PREFIX(f18)
#define casadi_f19 CASADI_PREFIX(f19)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f20 CASADI_PREFIX(f20)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_f6 CASADI_PREFIX(f6)
#define casadi_f7 CASADI_PREFIX(f7)
#define casadi_f8 CASADI_PREFIX(f8)
#define casadi_f9 CASADI_PREFIX(f9)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_dot(casadi_int n, const casadi_real* x, const casadi_real* y) {
  casadi_int i;
  casadi_real r = 0;
  for (i=0; i<n; ++i) r += *x++ * *y++;
  return r;
}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

static const casadi_int casadi_s0[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s1[122] = {16, 7, 0, 16, 32, 48, 64, 80, 96, 112, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s2[225] = {36, 6, 0, 36, 72, 108, 144, 180, 216, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35};
static const casadi_int casadi_s3[45] = {6, 6, 0, 6, 12, 18, 24, 30, 36, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5};

static const casadi_real casadi_c0[4] = {0., 0., 0., 1.};
static const casadi_real casadi_c1[9] = {1., 0., 0., 0., 1., 0., 0., 0., 1.};
static const casadi_real casadi_c2[16] = {1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1.};

/* TransToRp:(i0[4x4])->(o0[3x3],o1[3]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss, *tt;
  casadi_real *w0=w+0, *w1=w+16, *w2=w+25;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: @1 = @0[:12:4;:3] */
  for (rr=w1, ss=w0+0; ss!=w0+12; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 9, res[0]);
  /* #3: @2 = @0[12:15] */
  for (rr=w2, ss=w0+12; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #4: output[1][0] = @2 */
  casadi_copy(w2, 3, res[1]);
  return 0;
}

/* VecToso3:(i0[3])->(o0[3x3]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, *w5=w+9, *w6=w+12, *w7=w+21;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @4 = horzcat(@0, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #6: @4 = @4' */
  /* #7: @0 = @1[2] */
  for (rr=(&w0), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #8: @2 = 0 */
  w2 = 0.;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (-@3) */
  w3 = (- w3 );
  /* #11: @5 = horzcat(@0, @2, @3) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @5 = @5' */
  /* #13: @0 = @1[1] */
  for (rr=(&w0), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @0 = (-@0) */
  w0 = (- w0 );
  /* #15: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @3 = 0 */
  w3 = 0.;
  /* #17: @1 = horzcat(@0, @2, @3) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #18: @1 = @1' */
  /* #19: @6 = horzcat(@4, @5, @1) */
  rr=w6;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #20: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

/* Adjoint:(i0[4x4])->(o0[6x6]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+30, *w1=w+46, *w2=w+55, *w3=w+58, *w4=w+67, *w5=w+76, *w6=w+94, *w7=w+112, *w8=w+130, *w9=w+166;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: {@1, @2} = TransToRp(@0) */
  arg1[0]=w0;
  res1[0]=w1;
  res1[1]=w2;
  if (casadi_f3(arg1, res1, iw, w, 0)) return 1;
  /* #2: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #3: @4 = VecToso3(@2) */
  arg1[0]=w2;
  res1[0]=w4;
  if (casadi_f4(arg1, res1, iw, w, 0)) return 1;
  /* #4: @3 = mac(@4,@1,@3) */
  for (i=0, rr=w3; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w4+j, tt=w1+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #5: @5 = horzcat(@1, @3) */
  rr=w5;
  for (i=0, cs=w1; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<9; ++i) *rr++ = *cs++;
  /* #6: @6 = @5' */
  for (i=0, rr=w6, cs=w5; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #7: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #8: @5 = horzcat(@3, @1) */
  rr=w5;
  for (i=0, cs=w3; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<9; ++i) *rr++ = *cs++;
  /* #9: @7 = @5' */
  for (i=0, rr=w7, cs=w5; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #10: @8 = horzcat(@6, @7) */
  rr=w8;
  for (i=0, cs=w6; i<18; ++i) *rr++ = *cs++;
  for (i=0, cs=w7; i<18; ++i) *rr++ = *cs++;
  /* #11: @9 = @8' */
  for (i=0, rr=w9, cs=w8; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #12: output[0][0] = @9 */
  casadi_copy(w9, 36, res[0]);
  return 0;
}

/* TransToRp:(i0[4x4])->(o0[3x3],o1[3]) */
static int casadi_f6(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss, *tt;
  casadi_real *w0=w+0, *w1=w+16, *w2=w+25;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: @1 = @0[:12:4;:3] */
  for (rr=w1, ss=w0+0; ss!=w0+12; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #2: output[0][0] = @1 */
  casadi_copy(w1, 9, res[0]);
  /* #3: @2 = @0[12:15] */
  for (rr=w2, ss=w0+12; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #4: output[1][0] = @2 */
  casadi_copy(w2, 3, res[1]);
  return 0;
}

/* TransInv:(i0[4x4])->(o0[4x4]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+28, *w1=w+44, *w2=w+53, *w3=w+56, *w4=w+65, *w5=w+68, *w6=w+77, *w7=w+89, *w8=w+101, *w9=w+105;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: {@1, @2} = TransToRp(@0) */
  arg1[0]=w0;
  res1[0]=w1;
  res1[1]=w2;
  if (casadi_f6(arg1, res1, iw, w, 0)) return 1;
  /* #2: @3 = @1' */
  for (i=0, rr=w3, cs=w1; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #3: @4 = zeros(3x1) */
  casadi_clear(w4, 3);
  /* #4: @5 = @1' */
  for (i=0, rr=w5, cs=w1; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #5: @5 = (-@5) */
  for (i=0, rr=w5, cs=w5; i<9; ++i) *rr++ = (- *cs++ );
  /* #6: @4 = mac(@5,@2,@4) */
  for (i=0, rr=w4; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w5+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #7: @6 = horzcat(@3, @4) */
  rr=w6;
  for (i=0, cs=w3; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  /* #8: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #9: @8 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 4, w8);
  /* #10: @8 = @8' */
  /* #11: @0 = horzcat(@7, @8) */
  rr=w0;
  for (i=0, cs=w7; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<4; ++i) *rr++ = *cs++;
  /* #12: @9 = @0' */
  for (i=0, rr=w9, cs=w0; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #13: output[0][0] = @9 */
  casadi_copy(w9, 16, res[0]);
  return 0;
}

/* VecToso3:(i0[3])->(o0[3x3]) */
static int casadi_f8(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, *w5=w+9, *w6=w+12, *w7=w+21;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @4 = horzcat(@0, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #6: @4 = @4' */
  /* #7: @0 = @1[2] */
  for (rr=(&w0), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #8: @2 = 0 */
  w2 = 0.;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (-@3) */
  w3 = (- w3 );
  /* #11: @5 = horzcat(@0, @2, @3) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @5 = @5' */
  /* #13: @0 = @1[1] */
  for (rr=(&w0), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @0 = (-@0) */
  w0 = (- w0 );
  /* #15: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @3 = 0 */
  w3 = 0.;
  /* #17: @1 = horzcat(@0, @2, @3) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #18: @1 = @1' */
  /* #19: @6 = horzcat(@4, @5, @1) */
  rr=w6;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #20: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

/* VecTose3:(i0[6])->(o0[4x4]) */
static int casadi_f7(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+30, *w1=w+36, *w2=w+39, *w3=w+48, *w4=w+60, *w5=w+72, *w6=w+76, *w7=w+92;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w0);
  /* #1: @1 = @0[3:6] */
  for (rr=w1, ss=w0+3; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #2: @2 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w2;
  if (casadi_f8(arg1, res1, iw, w, 0)) return 1;
  /* #3: @1 = @0[:3] */
  for (rr=w1, ss=w0+0; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #4: @3 = horzcat(@2, @1) */
  rr=w3;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #5: @4 = @3' */
  for (i=0, rr=w4, cs=w3; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #6: @5 = zeros(4x1) */
  casadi_clear(w5, 4);
  /* #7: @6 = horzcat(@4, @5) */
  rr=w6;
  for (i=0, cs=w4; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<4; ++i) *rr++ = *cs++;
  /* #8: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #9: output[0][0] = @7 */
  casadi_copy(w7, 16, res[0]);
  return 0;
}

/* so3ToVec:(i0[3x3])->(o0[3]) */
static int casadi_f10(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 9, w0);
  /* #1: @1 = @0[5] */
  for (rr=(&w1), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = @0[6] */
  for (rr=(&w1), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #5: @1 = @0[1] */
  for (rr=(&w1), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #6: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  return 0;
}

/* NearZero:(i0)->(o0) */
static int casadi_f11(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(1, (&w0), (&w0)));
  /* #2: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #3: @1 = (@1<@0) */
  w1  = (w1<w0);
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* so3ToVec:(i0[3x3])->(o0[3]) */
static int casadi_f13(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real *rr, *ss;
  casadi_real *w0=w+0, w1;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 9, w0);
  /* #1: @1 = @0[5] */
  for (rr=(&w1), ss=w0+5; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #2: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  /* #3: @1 = @0[6] */
  for (rr=(&w1), ss=w0+6; ss!=w0+7; ss+=1) *rr++ = *ss;
  /* #4: output[0][1] = @1 */
  if (res[0]) res[0][1] = w1;
  /* #5: @1 = @0[1] */
  for (rr=(&w1), ss=w0+1; ss!=w0+2; ss+=1) *rr++ = *ss;
  /* #6: output[0][2] = @1 */
  if (res[0]) res[0][2] = w1;
  return 0;
}

/* NearZero:(i0)->(o0) */
static int casadi_f15(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(1, (&w0), (&w0)));
  /* #2: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #3: @1 = (@1<@0) */
  w1  = (w1<w0);
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* AxisAng3:(i0[3])->(o0[3x3],o1) */
static int casadi_f14(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+2, w1, w2, *w3=w+7;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(3, w0, w0));
  /* #2: @2 = NearZero(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w2);
  if (casadi_f15(arg1, res1, iw, w, 0)) return 1;
  /* #3: @2 = (!@2) */
  w2 = (! w2 );
  /* #4: @0 = (@0/@1) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) /= w1;
  /* #5: @0 = (@2?@0:0) */
  for (i=0, rr=w0, cs=w0; i<3; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #6: @3 = repmat(@0, 3) */
  for (i=0;i<3;++i) {
    casadi_copy(w0, 3, w3+ i*3);
  }
  /* #7: output[0][0] = @3 */
  casadi_copy(w3, 9, res[0]);
  /* #8: output[1][0] = @1 */
  if (res[1]) res[1][0] = w1;
  return 0;
}

/* NearZero:(i0)->(o0) */
static int casadi_f16(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(1, (&w0), (&w0)));
  /* #2: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #3: @1 = (@1<@0) */
  w1  = (w1<w0);
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* MatrixExp3:(i0[3x3])->(o0[3x3]) */
static int casadi_f12(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+16, *w1=w+25, w2, w3, *w4=w+30, *w5=w+39, w6, *w7=w+49, w8, *w9=w+59;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 9, w0);
  /* #1: @1 = so3ToVec(@0) */
  arg1[0]=w0;
  res1[0]=w1;
  if (casadi_f13(arg1, res1, iw, w, 0)) return 1;
  /* #2: {NULL, @2} = AxisAng3(@1) */
  arg1[0]=w1;
  res1[0]=0;
  res1[1]=(&w2);
  if (casadi_f14(arg1, res1, iw, w, 0)) return 1;
  /* #3: @3 = NearZero(@2) */
  arg1[0]=(&w2);
  res1[0]=(&w3);
  if (casadi_f16(arg1, res1, iw, w, 0)) return 1;
  /* #4: @4 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c1, 9, w4);
  /* #5: @4 = (@3?@4:0) */
  for (i=0, rr=w4, cs=w4; i<9; ++i) (*rr++)  = (w3?cs[i]:0);
  /* #6: @3 = (!@3) */
  w3 = (! w3 );
  /* #7: @5 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c1, 9, w5);
  /* #8: @6 = sin(@2) */
  w6 = sin( w2 );
  /* #9: @6 = (@6/@2) */
  w6 /= w2;
  /* #10: @7 = (@6*@0) */
  for (i=0, rr=w7, cs=w0; i<9; ++i) (*rr++)  = (w6*(*cs++));
  /* #11: @5 = (@5+@7) */
  for (i=0, rr=w5, cs=w7; i<9; ++i) (*rr++) += (*cs++);
  /* #12: @7 = zeros(3x3) */
  casadi_clear(w7, 9);
  /* #13: @6 = 1 */
  w6 = 1.;
  /* #14: @8 = cos(@2) */
  w8 = cos( w2 );
  /* #15: @6 = (@6-@8) */
  w6 -= w8;
  /* #16: @6 = (@6/@2) */
  w6 /= w2;
  /* #17: @6 = (@6/@2) */
  w6 /= w2;
  /* #18: @9 = (@6*@0) */
  for (i=0, rr=w9, cs=w0; i<9; ++i) (*rr++)  = (w6*(*cs++));
  /* #19: @7 = mac(@9,@0,@7) */
  for (i=0, rr=w7; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w9+j, tt=w0+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #20: @5 = (@5+@7) */
  for (i=0, rr=w5, cs=w7; i<9; ++i) (*rr++) += (*cs++);
  /* #21: @5 = (@3?@5:0) */
  for (i=0, rr=w5, cs=w5; i<9; ++i) (*rr++)  = (w3?cs[i]:0);
  /* #22: @4 = (@4+@5) */
  for (i=0, rr=w4, cs=w5; i<9; ++i) (*rr++) += (*cs++);
  /* #23: output[0][0] = @4 */
  casadi_copy(w4, 9, res[0]);
  return 0;
}

/* NearZero:(i0)->(o0) */
static int casadi_f18(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real w0, w1;
  /* #0: @0 = input[0][0] */
  w0 = arg[0] ? arg[0][0] : 0;
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(1, (&w0), (&w0)));
  /* #2: @0 = 2.22045e-16 */
  w0 = 2.2204460492503131e-16;
  /* #3: @1 = (@1<@0) */
  w1  = (w1<w0);
  /* #4: output[0][0] = @1 */
  if (res[0]) res[0][0] = w1;
  return 0;
}

/* AxisAng3:(i0[3])->(o0[3x3],o1) */
static int casadi_f17(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i;
  casadi_real **res1=res+2, *rr;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+2, w1, w2, *w3=w+7;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 3, w0);
  /* #1: @1 = ||@0||_F */
  w1 = sqrt(casadi_dot(3, w0, w0));
  /* #2: @2 = NearZero(@1) */
  arg1[0]=(&w1);
  res1[0]=(&w2);
  if (casadi_f18(arg1, res1, iw, w, 0)) return 1;
  /* #3: @2 = (!@2) */
  w2 = (! w2 );
  /* #4: @0 = (@0/@1) */
  for (i=0, rr=w0; i<3; ++i) (*rr++) /= w1;
  /* #5: @0 = (@2?@0:0) */
  for (i=0, rr=w0, cs=w0; i<3; ++i) (*rr++)  = (w2?cs[i]:0);
  /* #6: @3 = repmat(@0, 3) */
  for (i=0;i<3;++i) {
    casadi_copy(w0, 3, w3+ i*3);
  }
  /* #7: output[0][0] = @3 */
  casadi_copy(w3, 9, res[0]);
  /* #8: output[1][0] = @1 */
  if (res[1]) res[1][0] = w1;
  return 0;
}

/* MatrixExp6:(i0[4x4])->(o0[4x4]) */
static int casadi_f9(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+68, *w1=w+84, *w2=w+93, w3, w4, *w5=w+98, *w6=w+101, *w7=w+113, *w8=w+125, *w9=w+129, *w10=w+145, *w11=w+161, w12, w13, *w14=w+172, *w15=w+181, *w16=w+190;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 16, w0);
  /* #1: @1 = @0[:12:4;:3] */
  for (rr=w1, ss=w0+0; ss!=w0+12; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #2: @2 = so3ToVec(@1) */
  arg1[0]=w1;
  res1[0]=w2;
  if (casadi_f10(arg1, res1, iw, w, 0)) return 1;
  /* #3: @3 = ||@2||_F */
  w3 = sqrt(casadi_dot(3, w2, w2));
  /* #4: @4 = NearZero(@3) */
  arg1[0]=(&w3);
  res1[0]=(&w4);
  if (casadi_f11(arg1, res1, iw, w, 0)) return 1;
  /* #5: @1 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c1, 9, w1);
  /* #6: @5 = @0[12:15] */
  for (rr=w5, ss=w0+12; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #7: @6 = horzcat(@1, @5) */
  rr=w6;
  for (i=0, cs=w1; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  /* #8: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #9: @8 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 4, w8);
  /* #10: @8 = @8' */
  /* #11: @9 = horzcat(@7, @8) */
  rr=w9;
  for (i=0, cs=w7; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<4; ++i) *rr++ = *cs++;
  /* #12: @10 = @9' */
  for (i=0, rr=w10, cs=w9; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #13: @10 = (@4?@10:0) */
  for (i=0, rr=w10, cs=w10; i<16; ++i) (*rr++)  = (w4?cs[i]:0);
  /* #14: @4 = (!@4) */
  w4 = (! w4 );
  /* #15: @1 = @0[:12:4;:3] */
  for (rr=w1, ss=w0+0; ss!=w0+12; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #16: @11 = MatrixExp3(@1) */
  arg1[0]=w1;
  res1[0]=w11;
  if (casadi_f12(arg1, res1, iw, w, 0)) return 1;
  /* #17: @5 = zeros(3x1) */
  casadi_clear(w5, 3);
  /* #18: @1 = 
  [[1, 0, 0], 
   [0, 1, 0], 
   [0, 0, 1]] */
  casadi_copy(casadi_c1, 9, w1);
  /* #19: {NULL, @3} = AxisAng3(@2) */
  arg1[0]=w2;
  res1[0]=0;
  res1[1]=(&w3);
  if (casadi_f17(arg1, res1, iw, w, 0)) return 1;
  /* #20: @1 = (@1*@3) */
  for (i=0, rr=w1; i<9; ++i) (*rr++) *= w3;
  /* #21: @12 = 1 */
  w12 = 1.;
  /* #22: @13 = cos(@3) */
  w13 = cos( w3 );
  /* #23: @12 = (@12-@13) */
  w12 -= w13;
  /* #24: @14 = @0[:12:4;:3] */
  for (rr=w14, ss=w0+0; ss!=w0+12; ss+=4) for (tt=ss+0; tt!=ss+3; tt+=1) *rr++ = *tt;
  /* #25: @14 = (@14/@3) */
  for (i=0, rr=w14; i<9; ++i) (*rr++) /= w3;
  /* #26: @15 = (@12*@14) */
  for (i=0, rr=w15, cs=w14; i<9; ++i) (*rr++)  = (w12*(*cs++));
  /* #27: @1 = (@1+@15) */
  for (i=0, rr=w1, cs=w15; i<9; ++i) (*rr++) += (*cs++);
  /* #28: @15 = zeros(3x3) */
  casadi_clear(w15, 9);
  /* #29: @12 = sin(@3) */
  w12 = sin( w3 );
  /* #30: @12 = (@3-@12) */
  w12  = (w3-w12);
  /* #31: @16 = (@12*@14) */
  for (i=0, rr=w16, cs=w14; i<9; ++i) (*rr++)  = (w12*(*cs++));
  /* #32: @15 = mac(@16,@14,@15) */
  for (i=0, rr=w15; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w16+j, tt=w14+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #33: @1 = (@1+@15) */
  for (i=0, rr=w1, cs=w15; i<9; ++i) (*rr++) += (*cs++);
  /* #34: @2 = @0[12:15] */
  for (rr=w2, ss=w0+12; ss!=w0+15; ss+=1) *rr++ = *ss;
  /* #35: @5 = mac(@1,@2,@5) */
  for (i=0, rr=w5; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, ss=w1+j, tt=w2+i*3; k<3; ++k) *rr += ss[k*3]**tt++;
  /* #36: @5 = (@5/@3) */
  for (i=0, rr=w5; i<3; ++i) (*rr++) /= w3;
  /* #37: @7 = horzcat(@11, @5) */
  rr=w7;
  for (i=0, cs=w11; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  /* #38: @6 = @7' */
  for (i=0, rr=w6, cs=w7; i<4; ++i) for (j=0; j<3; ++j) rr[i+j*4] = *cs++;
  /* #39: @8 = [[0, 0, 0, 1]] */
  casadi_copy(casadi_c0, 4, w8);
  /* #40: @8 = @8' */
  /* #41: @0 = horzcat(@6, @8) */
  rr=w0;
  for (i=0, cs=w6; i<12; ++i) *rr++ = *cs++;
  for (i=0, cs=w8; i<4; ++i) *rr++ = *cs++;
  /* #42: @9 = @0' */
  for (i=0, rr=w9, cs=w0; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #43: @9 = (@4?@9:0) */
  for (i=0, rr=w9, cs=w9; i<16; ++i) (*rr++)  = (w4?cs[i]:0);
  /* #44: @10 = (@10+@9) */
  for (i=0, rr=w10, cs=w9; i<16; ++i) (*rr++) += (*cs++);
  /* #45: output[0][0] = @10 */
  casadi_copy(w10, 16, res[0]);
  return 0;
}

/* VecToso3:(i0[3])->(o0[3x3]) */
static int casadi_f20(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real *rr, *ss;
  const casadi_real *cs;
  casadi_real w0, *w1=w+1, w2, w3, *w4=w+6, *w5=w+9, *w6=w+12, *w7=w+21;
  /* #0: @0 = 0 */
  w0 = 0.;
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 3, w1);
  /* #2: @2 = @1[2] */
  for (rr=(&w2), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #3: @2 = (-@2) */
  w2 = (- w2 );
  /* #4: @3 = @1[1] */
  for (rr=(&w3), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #5: @4 = horzcat(@0, @2, @3) */
  rr=w4;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #6: @4 = @4' */
  /* #7: @0 = @1[2] */
  for (rr=(&w0), ss=w1+2; ss!=w1+3; ss+=1) *rr++ = *ss;
  /* #8: @2 = 0 */
  w2 = 0.;
  /* #9: @3 = @1[0] */
  for (rr=(&w3), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #10: @3 = (-@3) */
  w3 = (- w3 );
  /* #11: @5 = horzcat(@0, @2, @3) */
  rr=w5;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #12: @5 = @5' */
  /* #13: @0 = @1[1] */
  for (rr=(&w0), ss=w1+1; ss!=w1+2; ss+=1) *rr++ = *ss;
  /* #14: @0 = (-@0) */
  w0 = (- w0 );
  /* #15: @2 = @1[0] */
  for (rr=(&w2), ss=w1+0; ss!=w1+1; ss+=1) *rr++ = *ss;
  /* #16: @3 = 0 */
  w3 = 0.;
  /* #17: @1 = horzcat(@0, @2, @3) */
  rr=w1;
  *rr++ = w0;
  *rr++ = w2;
  *rr++ = w3;
  /* #18: @1 = @1' */
  /* #19: @6 = horzcat(@4, @5, @1) */
  rr=w6;
  for (i=0, cs=w4; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w5; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w1; i<3; ++i) *rr++ = *cs++;
  /* #20: @7 = @6' */
  for (i=0, rr=w7, cs=w6; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #21: output[0][0] = @7 */
  casadi_copy(w7, 9, res[0]);
  return 0;
}

/* adV:(i0[6])->(o0[6x6]) */
static int casadi_f19(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j;
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+1, *cs;
  casadi_real *w0=w+30, *w1=w+36, *w2=w+39, *w3=w+48, *w4=w+57, *w5=w+75, *w6=w+93, *w7=w+111, *w8=w+147;
  /* #0: @0 = input[0][0] */
  casadi_copy(arg[0], 6, w0);
  /* #1: @1 = @0[3:6] */
  for (rr=w1, ss=w0+3; ss!=w0+6; ss+=1) *rr++ = *ss;
  /* #2: @2 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w2;
  if (casadi_f20(arg1, res1, iw, w, 0)) return 1;
  /* #3: @1 = @0[:3] */
  for (rr=w1, ss=w0+0; ss!=w0+3; ss+=1) *rr++ = *ss;
  /* #4: @3 = VecToso3(@1) */
  arg1[0]=w1;
  res1[0]=w3;
  if (casadi_f20(arg1, res1, iw, w, 0)) return 1;
  /* #5: @4 = horzcat(@2, @3) */
  rr=w4;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w3; i<9; ++i) *rr++ = *cs++;
  /* #6: @5 = @4' */
  for (i=0, rr=w5, cs=w4; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #7: @3 = zeros(3x3) */
  casadi_clear(w3, 9);
  /* #8: @4 = horzcat(@3, @2) */
  rr=w4;
  for (i=0, cs=w3; i<9; ++i) *rr++ = *cs++;
  for (i=0, cs=w2; i<9; ++i) *rr++ = *cs++;
  /* #9: @6 = @4' */
  for (i=0, rr=w6, cs=w4; i<6; ++i) for (j=0; j<3; ++j) rr[i+j*6] = *cs++;
  /* #10: @7 = horzcat(@5, @6) */
  rr=w7;
  for (i=0, cs=w5; i<18; ++i) *rr++ = *cs++;
  for (i=0, cs=w6; i<18; ++i) *rr++ = *cs++;
  /* #11: @8 = @7' */
  for (i=0, rr=w8, cs=w7; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #12: output[0][0] = @8 */
  casadi_copy(w8, 36, res[0]);
  return 0;
}

/* pRNE:(i0[6],i1[6],i2[6],i3[6],i4[6],i5[6],i6[3],i7[6],i8[16x7],i9[36x6],i10[6x6])->(o0[6]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real **res1=res+1, *rr, *ss, *tt;
  const casadi_real **arg1=arg+11, *cs;
  casadi_real *w0=w+202, w1, *w2=w+209, *w3=w+215, *w4=w+327, *w5=w+343, *w6=w+379, *w7=w+415, *w8=w+421, *w9=w+637, *w10=w+679, *w11=w+682, *w12=w+688, *w13=w+694, *w14=w+710, *w15=w+726, *w16=w+742, *w17=w+778, *w18=w+814, w19, *w20=w+821, *w21=w+837, *w22=w+843, *w23=w+885, *w24=w+891, *w25=w+897, *w26=w+903, *w27=w+939, *w28=w+945, *w29=w+981, *w30=w+1017, *w31=w+1053, *w32=w+1089, *w33=w+1125, *w34=w+1161, *w35=w+1197, *w36=w+1233;
  /* #0: @0 = zeros(6x1) */
  casadi_clear(w0, 6);
  /* #1: @1 = 0 */
  w1 = 0.;
  /* #2: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #3: @3 = input[8][0] */
  casadi_copy(arg[8], 112, w3);
  /* #4: @4 = @3[96:112] */
  for (rr=w4, ss=w3+96; ss!=w3+112; ss+=1) *rr++ = *ss;
  /* #5: @4 = reshape(@4) */
  /* #6: @5 = Adjoint(@4) */
  arg1[0]=w4;
  res1[0]=w5;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #7: @6 = @5' */
  for (i=0, rr=w6, cs=w5; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #8: @7 = input[7][0] */
  casadi_copy(arg[7], 6, w7);
  /* #9: @2 = mac(@6,@7,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w6+j, tt=w7+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #10: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #11: @8 = input[9][0] */
  casadi_copy(arg[9], 216, w8);
  /* #12: @6 = @8[180:216] */
  for (rr=w6, ss=w8+180; ss!=w8+216; ss+=1) *rr++ = *ss;
  /* #13: @6 = reshape(@6) */
  /* #14: @9 = zeros(6x7) */
  casadi_clear(w9, 42);
  /* #15: @10 = input[6][0] */
  casadi_copy(arg[6], 3, w10);
  /* #16: @10 = (-@10) */
  for (i=0, rr=w10, cs=w10; i<3; ++i) *rr++ = (- *cs++ );
  /* #17: (@9[:3] = @10) */
  for (rr=w9+0, ss=w10; rr!=w9+3; rr+=1) *rr = *ss++;
  /* #18: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #19: @4 = zeros(4x4) */
  casadi_clear(w4, 16);
  /* #20: @5 = zeros(6x6) */
  casadi_clear(w5, 36);
  /* #21: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #22: @13 = zeros(4x4) */
  casadi_clear(w13, 16);
  /* #23: @14 = 
  [[1, 0, 0, 0], 
   [0, 1, 0, 0], 
   [0, 0, 1, 0], 
   [0, 0, 0, 1]] */
  casadi_copy(casadi_c2, 16, w14);
  /* #24: @15 = @3[:16] */
  for (rr=w15, ss=w3+0; ss!=w3+16; ss+=1) *rr++ = *ss;
  /* #25: @15 = reshape(@15) */
  /* #26: @13 = mac(@14,@15,@13) */
  for (i=0, rr=w13; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w14+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #27: @14 = TransInv(@13) */
  arg1[0]=w13;
  res1[0]=w14;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #28: @16 = Adjoint(@14) */
  arg1[0]=w14;
  res1[0]=w16;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #29: @17 = input[10][0] */
  casadi_copy(arg[10], 36, w17);
  /* #30: @18 = @17[:6] */
  for (rr=w18, ss=w17+0; ss!=w17+6; ss+=1) *rr++ = *ss;
  /* #31: @12 = mac(@16,@18,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w18+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #32: (@5[:6] = @12) */
  for (rr=w5+0, ss=w12; rr!=w5+6; rr+=1) *rr = *ss++;
  /* #33: @12 = @5[:6] */
  for (rr=w12, ss=w5+0; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #34: @18 = input[0][0] */
  casadi_copy(arg[0], 6, w18);
  /* #35: @19 = @18[0] */
  for (rr=(&w19), ss=w18+0; ss!=w18+1; ss+=1) *rr++ = *ss;
  /* #36: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #37: @12 = (-@12) */
  for (i=0, rr=w12, cs=w12; i<6; ++i) *rr++ = (- *cs++ );
  /* #38: @14 = VecTose3(@12) */
  arg1[0]=w12;
  res1[0]=w14;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #39: @15 = MatrixExp6(@14) */
  arg1[0]=w14;
  res1[0]=w15;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #40: @14 = @3[:16] */
  for (rr=w14, ss=w3+0; ss!=w3+16; ss+=1) *rr++ = *ss;
  /* #41: @14 = reshape(@14) */
  /* #42: @20 = TransInv(@14) */
  arg1[0]=w14;
  res1[0]=w20;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #43: @4 = mac(@15,@20,@4) */
  for (i=0, rr=w4; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w15+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #44: @16 = Adjoint(@4) */
  arg1[0]=w4;
  res1[0]=w16;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #45: @12 = @9[:6] */
  for (rr=w12, ss=w9+0; ss!=w9+6; ss+=1) *rr++ = *ss;
  /* #46: @11 = mac(@16,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #47: @12 = @5[:6] */
  for (rr=w12, ss=w5+0; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #48: @21 = input[5][0] */
  casadi_copy(arg[5], 6, w21);
  /* #49: @19 = @21[0] */
  for (rr=(&w19), ss=w21+0; ss!=w21+1; ss+=1) *rr++ = *ss;
  /* #50: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #51: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #52: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #53: @22 = zeros(6x7) */
  casadi_clear(w22, 42);
  /* #54: @23 = @5[:6] */
  for (rr=w23, ss=w5+0; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #55: @24 = input[1][0] */
  casadi_copy(arg[1], 6, w24);
  /* #56: @19 = @24[0] */
  for (rr=(&w19), ss=w24+0; ss!=w24+1; ss+=1) *rr++ = *ss;
  /* #57: @23 = (@23*@19) */
  for (i=0, rr=w23; i<6; ++i) (*rr++) *= w19;
  /* #58: (@22[6:12] = @23) */
  for (rr=w22+6, ss=w23; rr!=w22+12; rr+=1) *rr = *ss++;
  /* #59: @23 = @22[6:12] */
  for (rr=w23, ss=w22+6; ss!=w22+12; ss+=1) *rr++ = *ss;
  /* #60: @16 = adV(@23) */
  arg1[0]=w23;
  res1[0]=w16;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #61: @23 = @5[:6] */
  for (rr=w23, ss=w5+0; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #62: @12 = mac(@16,@23,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w23+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #63: @23 = input[4][0] */
  casadi_copy(arg[4], 6, w23);
  /* #64: @19 = @23[0] */
  for (rr=(&w19), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #65: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #66: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #67: (@9[6:12] = @11) */
  for (rr=w9+6, ss=w11; rr!=w9+12; rr+=1) *rr = *ss++;
  /* #68: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #69: @4 = zeros(4x4) */
  casadi_clear(w4, 16);
  /* #70: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #71: @15 = zeros(4x4) */
  casadi_clear(w15, 16);
  /* #72: @20 = @3[16:32] */
  for (rr=w20, ss=w3+16; ss!=w3+32; ss+=1) *rr++ = *ss;
  /* #73: @20 = reshape(@20) */
  /* #74: @15 = mac(@13,@20,@15) */
  for (i=0, rr=w15; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w13+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #75: @13 = TransInv(@15) */
  arg1[0]=w15;
  res1[0]=w13;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #76: @16 = Adjoint(@13) */
  arg1[0]=w13;
  res1[0]=w16;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #77: @25 = @17[6:12] */
  for (rr=w25, ss=w17+6; ss!=w17+12; ss+=1) *rr++ = *ss;
  /* #78: @12 = mac(@16,@25,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w16+j, tt=w25+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #79: @16 = @5; (@16[6:12] = @12) */
  casadi_copy(w5, 36, w16);
  for (rr=w16+6, ss=w12; rr!=w16+12; rr+=1) *rr = *ss++;
  /* #80: @12 = @16[6:12] */
  for (rr=w12, ss=w16+6; ss!=w16+12; ss+=1) *rr++ = *ss;
  /* #81: @19 = @18[1] */
  for (rr=(&w19), ss=w18+1; ss!=w18+2; ss+=1) *rr++ = *ss;
  /* #82: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #83: @12 = (-@12) */
  for (i=0, rr=w12, cs=w12; i<6; ++i) *rr++ = (- *cs++ );
  /* #84: @13 = VecTose3(@12) */
  arg1[0]=w12;
  res1[0]=w13;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #85: @20 = MatrixExp6(@13) */
  arg1[0]=w13;
  res1[0]=w20;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #86: @13 = @3[16:32] */
  for (rr=w13, ss=w3+16; ss!=w3+32; ss+=1) *rr++ = *ss;
  /* #87: @13 = reshape(@13) */
  /* #88: @14 = TransInv(@13) */
  arg1[0]=w13;
  res1[0]=w14;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #89: @4 = mac(@20,@14,@4) */
  for (i=0, rr=w4; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w20+j, tt=w14+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #90: @26 = Adjoint(@4) */
  arg1[0]=w4;
  res1[0]=w26;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #91: @12 = @9[6:12] */
  for (rr=w12, ss=w9+6; ss!=w9+12; ss+=1) *rr++ = *ss;
  /* #92: @11 = mac(@26,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w26+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #93: @12 = @16[6:12] */
  for (rr=w12, ss=w16+6; ss!=w16+12; ss+=1) *rr++ = *ss;
  /* #94: @19 = @21[1] */
  for (rr=(&w19), ss=w21+1; ss!=w21+2; ss+=1) *rr++ = *ss;
  /* #95: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #96: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #97: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #98: @25 = zeros(6x1) */
  casadi_clear(w25, 6);
  /* #99: @27 = @22[6:12] */
  for (rr=w27, ss=w22+6; ss!=w22+12; ss+=1) *rr++ = *ss;
  /* #100: @25 = mac(@26,@27,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w26+j, tt=w27+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #101: @27 = @16[6:12] */
  for (rr=w27, ss=w16+6; ss!=w16+12; ss+=1) *rr++ = *ss;
  /* #102: @19 = @24[1] */
  for (rr=(&w19), ss=w24+1; ss!=w24+2; ss+=1) *rr++ = *ss;
  /* #103: @27 = (@27*@19) */
  for (i=0, rr=w27; i<6; ++i) (*rr++) *= w19;
  /* #104: @25 = (@25+@27) */
  for (i=0, rr=w25, cs=w27; i<6; ++i) (*rr++) += (*cs++);
  /* #105: (@22[12:18] = @25) */
  for (rr=w22+12, ss=w25; rr!=w22+18; rr+=1) *rr = *ss++;
  /* #106: @25 = @22[12:18] */
  for (rr=w25, ss=w22+12; ss!=w22+18; ss+=1) *rr++ = *ss;
  /* #107: @28 = adV(@25) */
  arg1[0]=w25;
  res1[0]=w28;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #108: @25 = @16[6:12] */
  for (rr=w25, ss=w16+6; ss!=w16+12; ss+=1) *rr++ = *ss;
  /* #109: @12 = mac(@28,@25,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w28+j, tt=w25+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #110: @19 = @23[1] */
  for (rr=(&w19), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #111: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #112: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #113: (@9[12:18] = @11) */
  for (rr=w9+12, ss=w11; rr!=w9+18; rr+=1) *rr = *ss++;
  /* #114: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #115: @4 = zeros(4x4) */
  casadi_clear(w4, 16);
  /* #116: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #117: @20 = zeros(4x4) */
  casadi_clear(w20, 16);
  /* #118: @14 = @3[32:48] */
  for (rr=w14, ss=w3+32; ss!=w3+48; ss+=1) *rr++ = *ss;
  /* #119: @14 = reshape(@14) */
  /* #120: @20 = mac(@15,@14,@20) */
  for (i=0, rr=w20; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w15+j, tt=w14+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #121: @15 = TransInv(@20) */
  arg1[0]=w20;
  res1[0]=w15;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #122: @28 = Adjoint(@15) */
  arg1[0]=w15;
  res1[0]=w28;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #123: @25 = @17[12:18] */
  for (rr=w25, ss=w17+12; ss!=w17+18; ss+=1) *rr++ = *ss;
  /* #124: @12 = mac(@28,@25,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w28+j, tt=w25+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #125: @28 = @16; (@28[12:18] = @12) */
  casadi_copy(w16, 36, w28);
  for (rr=w28+12, ss=w12; rr!=w28+18; rr+=1) *rr = *ss++;
  /* #126: @12 = @28[12:18] */
  for (rr=w12, ss=w28+12; ss!=w28+18; ss+=1) *rr++ = *ss;
  /* #127: @19 = @18[2] */
  for (rr=(&w19), ss=w18+2; ss!=w18+3; ss+=1) *rr++ = *ss;
  /* #128: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #129: @12 = (-@12) */
  for (i=0, rr=w12, cs=w12; i<6; ++i) *rr++ = (- *cs++ );
  /* #130: @15 = VecTose3(@12) */
  arg1[0]=w12;
  res1[0]=w15;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #131: @14 = MatrixExp6(@15) */
  arg1[0]=w15;
  res1[0]=w14;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #132: @15 = @3[32:48] */
  for (rr=w15, ss=w3+32; ss!=w3+48; ss+=1) *rr++ = *ss;
  /* #133: @15 = reshape(@15) */
  /* #134: @13 = TransInv(@15) */
  arg1[0]=w15;
  res1[0]=w13;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #135: @4 = mac(@14,@13,@4) */
  for (i=0, rr=w4; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w14+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #136: @29 = Adjoint(@4) */
  arg1[0]=w4;
  res1[0]=w29;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #137: @12 = @9[12:18] */
  for (rr=w12, ss=w9+12; ss!=w9+18; ss+=1) *rr++ = *ss;
  /* #138: @11 = mac(@29,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w29+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #139: @12 = @28[12:18] */
  for (rr=w12, ss=w28+12; ss!=w28+18; ss+=1) *rr++ = *ss;
  /* #140: @19 = @21[2] */
  for (rr=(&w19), ss=w21+2; ss!=w21+3; ss+=1) *rr++ = *ss;
  /* #141: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #142: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #143: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #144: @25 = zeros(6x1) */
  casadi_clear(w25, 6);
  /* #145: @27 = @22[12:18] */
  for (rr=w27, ss=w22+12; ss!=w22+18; ss+=1) *rr++ = *ss;
  /* #146: @25 = mac(@29,@27,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w29+j, tt=w27+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #147: @27 = @28[12:18] */
  for (rr=w27, ss=w28+12; ss!=w28+18; ss+=1) *rr++ = *ss;
  /* #148: @19 = @24[2] */
  for (rr=(&w19), ss=w24+2; ss!=w24+3; ss+=1) *rr++ = *ss;
  /* #149: @27 = (@27*@19) */
  for (i=0, rr=w27; i<6; ++i) (*rr++) *= w19;
  /* #150: @25 = (@25+@27) */
  for (i=0, rr=w25, cs=w27; i<6; ++i) (*rr++) += (*cs++);
  /* #151: (@22[18:24] = @25) */
  for (rr=w22+18, ss=w25; rr!=w22+24; rr+=1) *rr = *ss++;
  /* #152: @25 = @22[18:24] */
  for (rr=w25, ss=w22+18; ss!=w22+24; ss+=1) *rr++ = *ss;
  /* #153: @30 = adV(@25) */
  arg1[0]=w25;
  res1[0]=w30;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #154: @25 = @28[12:18] */
  for (rr=w25, ss=w28+12; ss!=w28+18; ss+=1) *rr++ = *ss;
  /* #155: @12 = mac(@30,@25,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w30+j, tt=w25+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #156: @19 = @23[2] */
  for (rr=(&w19), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #157: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #158: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #159: (@9[18:24] = @11) */
  for (rr=w9+18, ss=w11; rr!=w9+24; rr+=1) *rr = *ss++;
  /* #160: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #161: @4 = zeros(4x4) */
  casadi_clear(w4, 16);
  /* #162: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #163: @14 = zeros(4x4) */
  casadi_clear(w14, 16);
  /* #164: @13 = @3[48:64] */
  for (rr=w13, ss=w3+48; ss!=w3+64; ss+=1) *rr++ = *ss;
  /* #165: @13 = reshape(@13) */
  /* #166: @14 = mac(@20,@13,@14) */
  for (i=0, rr=w14; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w20+j, tt=w13+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #167: @20 = TransInv(@14) */
  arg1[0]=w14;
  res1[0]=w20;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #168: @30 = Adjoint(@20) */
  arg1[0]=w20;
  res1[0]=w30;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #169: @25 = @17[18:24] */
  for (rr=w25, ss=w17+18; ss!=w17+24; ss+=1) *rr++ = *ss;
  /* #170: @12 = mac(@30,@25,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w30+j, tt=w25+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #171: @30 = @28; (@30[18:24] = @12) */
  casadi_copy(w28, 36, w30);
  for (rr=w30+18, ss=w12; rr!=w30+24; rr+=1) *rr = *ss++;
  /* #172: @12 = @30[18:24] */
  for (rr=w12, ss=w30+18; ss!=w30+24; ss+=1) *rr++ = *ss;
  /* #173: @19 = @18[3] */
  for (rr=(&w19), ss=w18+3; ss!=w18+4; ss+=1) *rr++ = *ss;
  /* #174: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #175: @12 = (-@12) */
  for (i=0, rr=w12, cs=w12; i<6; ++i) *rr++ = (- *cs++ );
  /* #176: @20 = VecTose3(@12) */
  arg1[0]=w12;
  res1[0]=w20;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #177: @13 = MatrixExp6(@20) */
  arg1[0]=w20;
  res1[0]=w13;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #178: @20 = @3[48:64] */
  for (rr=w20, ss=w3+48; ss!=w3+64; ss+=1) *rr++ = *ss;
  /* #179: @20 = reshape(@20) */
  /* #180: @15 = TransInv(@20) */
  arg1[0]=w20;
  res1[0]=w15;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #181: @4 = mac(@13,@15,@4) */
  for (i=0, rr=w4; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w13+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #182: @31 = Adjoint(@4) */
  arg1[0]=w4;
  res1[0]=w31;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #183: @12 = @9[18:24] */
  for (rr=w12, ss=w9+18; ss!=w9+24; ss+=1) *rr++ = *ss;
  /* #184: @11 = mac(@31,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w31+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #185: @12 = @30[18:24] */
  for (rr=w12, ss=w30+18; ss!=w30+24; ss+=1) *rr++ = *ss;
  /* #186: @19 = @21[3] */
  for (rr=(&w19), ss=w21+3; ss!=w21+4; ss+=1) *rr++ = *ss;
  /* #187: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #188: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #189: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #190: @25 = zeros(6x1) */
  casadi_clear(w25, 6);
  /* #191: @27 = @22[18:24] */
  for (rr=w27, ss=w22+18; ss!=w22+24; ss+=1) *rr++ = *ss;
  /* #192: @25 = mac(@31,@27,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w31+j, tt=w27+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #193: @27 = @30[18:24] */
  for (rr=w27, ss=w30+18; ss!=w30+24; ss+=1) *rr++ = *ss;
  /* #194: @19 = @24[3] */
  for (rr=(&w19), ss=w24+3; ss!=w24+4; ss+=1) *rr++ = *ss;
  /* #195: @27 = (@27*@19) */
  for (i=0, rr=w27; i<6; ++i) (*rr++) *= w19;
  /* #196: @25 = (@25+@27) */
  for (i=0, rr=w25, cs=w27; i<6; ++i) (*rr++) += (*cs++);
  /* #197: (@22[24:30] = @25) */
  for (rr=w22+24, ss=w25; rr!=w22+30; rr+=1) *rr = *ss++;
  /* #198: @25 = @22[24:30] */
  for (rr=w25, ss=w22+24; ss!=w22+30; ss+=1) *rr++ = *ss;
  /* #199: @32 = adV(@25) */
  arg1[0]=w25;
  res1[0]=w32;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #200: @25 = @30[18:24] */
  for (rr=w25, ss=w30+18; ss!=w30+24; ss+=1) *rr++ = *ss;
  /* #201: @12 = mac(@32,@25,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w32+j, tt=w25+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #202: @19 = @23[3] */
  for (rr=(&w19), ss=w23+3; ss!=w23+4; ss+=1) *rr++ = *ss;
  /* #203: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #204: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #205: (@9[24:30] = @11) */
  for (rr=w9+24, ss=w11; rr!=w9+30; rr+=1) *rr = *ss++;
  /* #206: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #207: @4 = zeros(4x4) */
  casadi_clear(w4, 16);
  /* #208: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #209: @13 = zeros(4x4) */
  casadi_clear(w13, 16);
  /* #210: @15 = @3[64:80] */
  for (rr=w15, ss=w3+64; ss!=w3+80; ss+=1) *rr++ = *ss;
  /* #211: @15 = reshape(@15) */
  /* #212: @13 = mac(@14,@15,@13) */
  for (i=0, rr=w13; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w14+j, tt=w15+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #213: @14 = TransInv(@13) */
  arg1[0]=w13;
  res1[0]=w14;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #214: @32 = Adjoint(@14) */
  arg1[0]=w14;
  res1[0]=w32;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #215: @25 = @17[24:30] */
  for (rr=w25, ss=w17+24; ss!=w17+30; ss+=1) *rr++ = *ss;
  /* #216: @12 = mac(@32,@25,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w32+j, tt=w25+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #217: @32 = @30; (@32[24:30] = @12) */
  casadi_copy(w30, 36, w32);
  for (rr=w32+24, ss=w12; rr!=w32+30; rr+=1) *rr = *ss++;
  /* #218: @12 = @32[24:30] */
  for (rr=w12, ss=w32+24; ss!=w32+30; ss+=1) *rr++ = *ss;
  /* #219: @19 = @18[4] */
  for (rr=(&w19), ss=w18+4; ss!=w18+5; ss+=1) *rr++ = *ss;
  /* #220: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #221: @12 = (-@12) */
  for (i=0, rr=w12, cs=w12; i<6; ++i) *rr++ = (- *cs++ );
  /* #222: @14 = VecTose3(@12) */
  arg1[0]=w12;
  res1[0]=w14;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #223: @15 = MatrixExp6(@14) */
  arg1[0]=w14;
  res1[0]=w15;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #224: @14 = @3[64:80] */
  for (rr=w14, ss=w3+64; ss!=w3+80; ss+=1) *rr++ = *ss;
  /* #225: @14 = reshape(@14) */
  /* #226: @20 = TransInv(@14) */
  arg1[0]=w14;
  res1[0]=w20;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #227: @4 = mac(@15,@20,@4) */
  for (i=0, rr=w4; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w15+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #228: @33 = Adjoint(@4) */
  arg1[0]=w4;
  res1[0]=w33;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #229: @12 = @9[24:30] */
  for (rr=w12, ss=w9+24; ss!=w9+30; ss+=1) *rr++ = *ss;
  /* #230: @11 = mac(@33,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w33+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #231: @12 = @32[24:30] */
  for (rr=w12, ss=w32+24; ss!=w32+30; ss+=1) *rr++ = *ss;
  /* #232: @19 = @21[4] */
  for (rr=(&w19), ss=w21+4; ss!=w21+5; ss+=1) *rr++ = *ss;
  /* #233: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #234: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #235: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #236: @25 = zeros(6x1) */
  casadi_clear(w25, 6);
  /* #237: @27 = @22[24:30] */
  for (rr=w27, ss=w22+24; ss!=w22+30; ss+=1) *rr++ = *ss;
  /* #238: @25 = mac(@33,@27,@25) */
  for (i=0, rr=w25; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w33+j, tt=w27+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #239: @27 = @32[24:30] */
  for (rr=w27, ss=w32+24; ss!=w32+30; ss+=1) *rr++ = *ss;
  /* #240: @19 = @24[4] */
  for (rr=(&w19), ss=w24+4; ss!=w24+5; ss+=1) *rr++ = *ss;
  /* #241: @27 = (@27*@19) */
  for (i=0, rr=w27; i<6; ++i) (*rr++) *= w19;
  /* #242: @25 = (@25+@27) */
  for (i=0, rr=w25, cs=w27; i<6; ++i) (*rr++) += (*cs++);
  /* #243: (@22[30:36] = @25) */
  for (rr=w22+30, ss=w25; rr!=w22+36; rr+=1) *rr = *ss++;
  /* #244: @25 = @22[30:36] */
  for (rr=w25, ss=w22+30; ss!=w22+36; ss+=1) *rr++ = *ss;
  /* #245: @34 = adV(@25) */
  arg1[0]=w25;
  res1[0]=w34;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #246: @25 = @32[24:30] */
  for (rr=w25, ss=w32+24; ss!=w32+30; ss+=1) *rr++ = *ss;
  /* #247: @12 = mac(@34,@25,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w34+j, tt=w25+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #248: @19 = @23[4] */
  for (rr=(&w19), ss=w23+4; ss!=w23+5; ss+=1) *rr++ = *ss;
  /* #249: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #250: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #251: (@9[30:36] = @11) */
  for (rr=w9+30, ss=w11; rr!=w9+36; rr+=1) *rr = *ss++;
  /* #252: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #253: @4 = zeros(4x4) */
  casadi_clear(w4, 16);
  /* #254: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #255: @15 = zeros(4x4) */
  casadi_clear(w15, 16);
  /* #256: @20 = @3[80:96] */
  for (rr=w20, ss=w3+80; ss!=w3+96; ss+=1) *rr++ = *ss;
  /* #257: @20 = reshape(@20) */
  /* #258: @15 = mac(@13,@20,@15) */
  for (i=0, rr=w15; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w13+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #259: @13 = TransInv(@15) */
  arg1[0]=w15;
  res1[0]=w13;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #260: @34 = Adjoint(@13) */
  arg1[0]=w13;
  res1[0]=w34;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #261: @25 = @17[30:36] */
  for (rr=w25, ss=w17+30; ss!=w17+36; ss+=1) *rr++ = *ss;
  /* #262: @12 = mac(@34,@25,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w34+j, tt=w25+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #263: @34 = @32; (@34[30:36] = @12) */
  casadi_copy(w32, 36, w34);
  for (rr=w34+30, ss=w12; rr!=w34+36; rr+=1) *rr = *ss++;
  /* #264: @12 = @34[30:36] */
  for (rr=w12, ss=w34+30; ss!=w34+36; ss+=1) *rr++ = *ss;
  /* #265: @19 = @18[5] */
  for (rr=(&w19), ss=w18+5; ss!=w18+6; ss+=1) *rr++ = *ss;
  /* #266: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #267: @12 = (-@12) */
  for (i=0, rr=w12, cs=w12; i<6; ++i) *rr++ = (- *cs++ );
  /* #268: @13 = VecTose3(@12) */
  arg1[0]=w12;
  res1[0]=w13;
  if (casadi_f7(arg1, res1, iw, w, 0)) return 1;
  /* #269: @15 = MatrixExp6(@13) */
  arg1[0]=w13;
  res1[0]=w15;
  if (casadi_f9(arg1, res1, iw, w, 0)) return 1;
  /* #270: @13 = @3[80:96] */
  for (rr=w13, ss=w3+80; ss!=w3+96; ss+=1) *rr++ = *ss;
  /* #271: @13 = reshape(@13) */
  /* #272: @20 = TransInv(@13) */
  arg1[0]=w13;
  res1[0]=w20;
  if (casadi_f5(arg1, res1, iw, w, 0)) return 1;
  /* #273: @4 = mac(@15,@20,@4) */
  for (i=0, rr=w4; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, ss=w15+j, tt=w20+i*4; k<4; ++k) *rr += ss[k*4]**tt++;
  /* #274: @17 = Adjoint(@4) */
  arg1[0]=w4;
  res1[0]=w17;
  if (casadi_f2(arg1, res1, iw, w, 0)) return 1;
  /* #275: @12 = @9[30:36] */
  for (rr=w12, ss=w9+30; ss!=w9+36; ss+=1) *rr++ = *ss;
  /* #276: @11 = mac(@17,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w17+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #277: @12 = @34[30:36] */
  for (rr=w12, ss=w34+30; ss!=w34+36; ss+=1) *rr++ = *ss;
  /* #278: @19 = @21[5] */
  for (rr=(&w19), ss=w21+5; ss!=w21+6; ss+=1) *rr++ = *ss;
  /* #279: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #280: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #281: @12 = zeros(6x1) */
  casadi_clear(w12, 6);
  /* #282: @21 = zeros(6x1) */
  casadi_clear(w21, 6);
  /* #283: @18 = @22[30:36] */
  for (rr=w18, ss=w22+30; ss!=w22+36; ss+=1) *rr++ = *ss;
  /* #284: @21 = mac(@17,@18,@21) */
  for (i=0, rr=w21; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w17+j, tt=w18+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #285: @18 = @34[30:36] */
  for (rr=w18, ss=w34+30; ss!=w34+36; ss+=1) *rr++ = *ss;
  /* #286: @19 = @24[5] */
  for (rr=(&w19), ss=w24+5; ss!=w24+6; ss+=1) *rr++ = *ss;
  /* #287: @18 = (@18*@19) */
  for (i=0, rr=w18; i<6; ++i) (*rr++) *= w19;
  /* #288: @21 = (@21+@18) */
  for (i=0, rr=w21, cs=w18; i<6; ++i) (*rr++) += (*cs++);
  /* #289: (@22[36:42] = @21) */
  for (rr=w22+36, ss=w21; rr!=w22+42; rr+=1) *rr = *ss++;
  /* #290: @21 = @22[36:42] */
  for (rr=w21, ss=w22+36; ss!=w22+42; ss+=1) *rr++ = *ss;
  /* #291: @35 = adV(@21) */
  arg1[0]=w21;
  res1[0]=w35;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #292: @21 = @34[30:36] */
  for (rr=w21, ss=w34+30; ss!=w34+36; ss+=1) *rr++ = *ss;
  /* #293: @12 = mac(@35,@21,@12) */
  for (i=0, rr=w12; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w35+j, tt=w21+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #294: @19 = @23[5] */
  for (rr=(&w19), ss=w23+5; ss!=w23+6; ss+=1) *rr++ = *ss;
  /* #295: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #296: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #297: (@9[36:42] = @11) */
  for (rr=w9+36, ss=w11; rr!=w9+42; rr+=1) *rr = *ss++;
  /* #298: @11 = @9[36:42] */
  for (rr=w11, ss=w9+36; ss!=w9+42; ss+=1) *rr++ = *ss;
  /* #299: @7 = mac(@6,@11,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w6+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #300: @2 = (@2+@7) */
  for (i=0, rr=w2, cs=w7; i<6; ++i) (*rr++) += (*cs++);
  /* #301: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #302: @35 = zeros(6x6) */
  casadi_clear(w35, 36);
  /* #303: @36 = zeros(6x7) */
  casadi_clear(w36, 42);
  /* #304: @11 = @5[:6] */
  for (rr=w11, ss=w5+0; ss!=w5+6; ss+=1) *rr++ = *ss;
  /* #305: @19 = @23[0] */
  for (rr=(&w19), ss=w23+0; ss!=w23+1; ss+=1) *rr++ = *ss;
  /* #306: @11 = (@11*@19) */
  for (i=0, rr=w11; i<6; ++i) (*rr++) *= w19;
  /* #307: (@36[6:12] = @11) */
  for (rr=w36+6, ss=w11; rr!=w36+12; rr+=1) *rr = *ss++;
  /* #308: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #309: @12 = @36[6:12] */
  for (rr=w12, ss=w36+6; ss!=w36+12; ss+=1) *rr++ = *ss;
  /* #310: @11 = mac(@26,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w26+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #311: @12 = @16[6:12] */
  for (rr=w12, ss=w16+6; ss!=w16+12; ss+=1) *rr++ = *ss;
  /* #312: @19 = @23[1] */
  for (rr=(&w19), ss=w23+1; ss!=w23+2; ss+=1) *rr++ = *ss;
  /* #313: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #314: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #315: (@36[12:18] = @11) */
  for (rr=w36+12, ss=w11; rr!=w36+18; rr+=1) *rr = *ss++;
  /* #316: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #317: @12 = @36[12:18] */
  for (rr=w12, ss=w36+12; ss!=w36+18; ss+=1) *rr++ = *ss;
  /* #318: @11 = mac(@29,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w29+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #319: @12 = @28[12:18] */
  for (rr=w12, ss=w28+12; ss!=w28+18; ss+=1) *rr++ = *ss;
  /* #320: @19 = @23[2] */
  for (rr=(&w19), ss=w23+2; ss!=w23+3; ss+=1) *rr++ = *ss;
  /* #321: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #322: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #323: (@36[18:24] = @11) */
  for (rr=w36+18, ss=w11; rr!=w36+24; rr+=1) *rr = *ss++;
  /* #324: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #325: @12 = @36[18:24] */
  for (rr=w12, ss=w36+18; ss!=w36+24; ss+=1) *rr++ = *ss;
  /* #326: @11 = mac(@31,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w31+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #327: @12 = @30[18:24] */
  for (rr=w12, ss=w30+18; ss!=w30+24; ss+=1) *rr++ = *ss;
  /* #328: @19 = @23[3] */
  for (rr=(&w19), ss=w23+3; ss!=w23+4; ss+=1) *rr++ = *ss;
  /* #329: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #330: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #331: (@36[24:30] = @11) */
  for (rr=w36+24, ss=w11; rr!=w36+30; rr+=1) *rr = *ss++;
  /* #332: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #333: @12 = @36[24:30] */
  for (rr=w12, ss=w36+24; ss!=w36+30; ss+=1) *rr++ = *ss;
  /* #334: @11 = mac(@33,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w33+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #335: @12 = @32[24:30] */
  for (rr=w12, ss=w32+24; ss!=w32+30; ss+=1) *rr++ = *ss;
  /* #336: @19 = @23[4] */
  for (rr=(&w19), ss=w23+4; ss!=w23+5; ss+=1) *rr++ = *ss;
  /* #337: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #338: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #339: (@36[30:36] = @11) */
  for (rr=w36+30, ss=w11; rr!=w36+36; rr+=1) *rr = *ss++;
  /* #340: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #341: @12 = @36[30:36] */
  for (rr=w12, ss=w36+30; ss!=w36+36; ss+=1) *rr++ = *ss;
  /* #342: @11 = mac(@17,@12,@11) */
  for (i=0, rr=w11; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w17+j, tt=w12+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #343: @12 = @34[30:36] */
  for (rr=w12, ss=w34+30; ss!=w34+36; ss+=1) *rr++ = *ss;
  /* #344: @19 = @23[5] */
  for (rr=(&w19), ss=w23+5; ss!=w23+6; ss+=1) *rr++ = *ss;
  /* #345: @12 = (@12*@19) */
  for (i=0, rr=w12; i<6; ++i) (*rr++) *= w19;
  /* #346: @11 = (@11+@12) */
  for (i=0, rr=w11, cs=w12; i<6; ++i) (*rr++) += (*cs++);
  /* #347: (@36[36:42] = @11) */
  for (rr=w36+36, ss=w11; rr!=w36+42; rr+=1) *rr = *ss++;
  /* #348: @11 = @36[36:42] */
  for (rr=w11, ss=w36+36; ss!=w36+42; ss+=1) *rr++ = *ss;
  /* #349: @32 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w32;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #350: @35 = mac(@6,@32,@35) */
  for (i=0, rr=w35; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w6+j, tt=w32+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #351: @32 = zeros(6x6) */
  casadi_clear(w32, 36);
  /* #352: @11 = @22[36:42] */
  for (rr=w11, ss=w22+36; ss!=w22+42; ss+=1) *rr++ = *ss;
  /* #353: @30 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w30;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #354: @28 = @30' */
  for (i=0, rr=w28, cs=w30; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #355: @32 = mac(@28,@6,@32) */
  for (i=0, rr=w32; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w28+j, tt=w6+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #356: @35 = (@35-@32) */
  for (i=0, rr=w35, cs=w32; i<36; ++i) (*rr++) -= (*cs++);
  /* #357: @11 = @36[36:42] */
  for (rr=w11, ss=w36+36; ss!=w36+42; ss+=1) *rr++ = *ss;
  /* #358: @7 = mac(@35,@11,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w35+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #359: @2 = (@2+@7) */
  for (i=0, rr=w2, cs=w7; i<6; ++i) (*rr++) += (*cs++);
  /* #360: @7 = @2' */
  casadi_copy(w2, 6, w7);
  /* #361: @11 = @34[30:36] */
  for (rr=w11, ss=w34+30; ss!=w34+36; ss+=1) *rr++ = *ss;
  /* #362: @1 = mac(@7,@11,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w7+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #363: (@0[5] = @1) */
  for (rr=w0+5, ss=(&w1); rr!=w0+6; rr+=1) *rr = *ss++;
  /* #364: @1 = 0 */
  w1 = 0.;
  /* #365: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #366: @35 = @17' */
  for (i=0, rr=w35, cs=w17; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #367: @7 = mac(@35,@2,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w35+j, tt=w2+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #368: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #369: @35 = @8[144:180] */
  for (rr=w35, ss=w8+144; ss!=w8+180; ss+=1) *rr++ = *ss;
  /* #370: @35 = reshape(@35) */
  /* #371: @11 = @9[30:36] */
  for (rr=w11, ss=w9+30; ss!=w9+36; ss+=1) *rr++ = *ss;
  /* #372: @2 = mac(@35,@11,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w35+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #373: @7 = (@7+@2) */
  for (i=0, rr=w7, cs=w2; i<6; ++i) (*rr++) += (*cs++);
  /* #374: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #375: @17 = zeros(6x6) */
  casadi_clear(w17, 36);
  /* #376: @11 = @36[30:36] */
  for (rr=w11, ss=w36+30; ss!=w36+36; ss+=1) *rr++ = *ss;
  /* #377: @32 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w32;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #378: @17 = mac(@35,@32,@17) */
  for (i=0, rr=w17; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w35+j, tt=w32+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #379: @32 = zeros(6x6) */
  casadi_clear(w32, 36);
  /* #380: @11 = @22[30:36] */
  for (rr=w11, ss=w22+30; ss!=w22+36; ss+=1) *rr++ = *ss;
  /* #381: @28 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w28;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #382: @6 = @28' */
  for (i=0, rr=w6, cs=w28; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #383: @32 = mac(@6,@35,@32) */
  for (i=0, rr=w32; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w6+j, tt=w35+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #384: @17 = (@17-@32) */
  for (i=0, rr=w17, cs=w32; i<36; ++i) (*rr++) -= (*cs++);
  /* #385: @11 = @36[30:36] */
  for (rr=w11, ss=w36+30; ss!=w36+36; ss+=1) *rr++ = *ss;
  /* #386: @2 = mac(@17,@11,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w17+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #387: @7 = (@7+@2) */
  for (i=0, rr=w7, cs=w2; i<6; ++i) (*rr++) += (*cs++);
  /* #388: @2 = @7' */
  casadi_copy(w7, 6, w2);
  /* #389: @11 = @34[24:30] */
  for (rr=w11, ss=w34+24; ss!=w34+30; ss+=1) *rr++ = *ss;
  /* #390: @1 = mac(@2,@11,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #391: (@0[4] = @1) */
  for (rr=w0+4, ss=(&w1); rr!=w0+5; rr+=1) *rr = *ss++;
  /* #392: @1 = 0 */
  w1 = 0.;
  /* #393: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #394: @17 = @33' */
  for (i=0, rr=w17, cs=w33; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #395: @2 = mac(@17,@7,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w17+j, tt=w7+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #396: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #397: @17 = @8[108:144] */
  for (rr=w17, ss=w8+108; ss!=w8+144; ss+=1) *rr++ = *ss;
  /* #398: @17 = reshape(@17) */
  /* #399: @11 = @9[24:30] */
  for (rr=w11, ss=w9+24; ss!=w9+30; ss+=1) *rr++ = *ss;
  /* #400: @7 = mac(@17,@11,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w17+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #401: @2 = (@2+@7) */
  for (i=0, rr=w2, cs=w7; i<6; ++i) (*rr++) += (*cs++);
  /* #402: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #403: @33 = zeros(6x6) */
  casadi_clear(w33, 36);
  /* #404: @11 = @36[24:30] */
  for (rr=w11, ss=w36+24; ss!=w36+30; ss+=1) *rr++ = *ss;
  /* #405: @32 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w32;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #406: @33 = mac(@17,@32,@33) */
  for (i=0, rr=w33; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w17+j, tt=w32+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #407: @32 = zeros(6x6) */
  casadi_clear(w32, 36);
  /* #408: @11 = @22[24:30] */
  for (rr=w11, ss=w22+24; ss!=w22+30; ss+=1) *rr++ = *ss;
  /* #409: @6 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w6;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #410: @35 = @6' */
  for (i=0, rr=w35, cs=w6; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #411: @32 = mac(@35,@17,@32) */
  for (i=0, rr=w32; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w35+j, tt=w17+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #412: @33 = (@33-@32) */
  for (i=0, rr=w33, cs=w32; i<36; ++i) (*rr++) -= (*cs++);
  /* #413: @11 = @36[24:30] */
  for (rr=w11, ss=w36+24; ss!=w36+30; ss+=1) *rr++ = *ss;
  /* #414: @7 = mac(@33,@11,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w33+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #415: @2 = (@2+@7) */
  for (i=0, rr=w2, cs=w7; i<6; ++i) (*rr++) += (*cs++);
  /* #416: @7 = @2' */
  casadi_copy(w2, 6, w7);
  /* #417: @11 = @34[18:24] */
  for (rr=w11, ss=w34+18; ss!=w34+24; ss+=1) *rr++ = *ss;
  /* #418: @1 = mac(@7,@11,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w7+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #419: (@0[3] = @1) */
  for (rr=w0+3, ss=(&w1); rr!=w0+4; rr+=1) *rr = *ss++;
  /* #420: @1 = 0 */
  w1 = 0.;
  /* #421: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #422: @33 = @31' */
  for (i=0, rr=w33, cs=w31; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #423: @7 = mac(@33,@2,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w33+j, tt=w2+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #424: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #425: @33 = @8[72:108] */
  for (rr=w33, ss=w8+72; ss!=w8+108; ss+=1) *rr++ = *ss;
  /* #426: @33 = reshape(@33) */
  /* #427: @11 = @9[18:24] */
  for (rr=w11, ss=w9+18; ss!=w9+24; ss+=1) *rr++ = *ss;
  /* #428: @2 = mac(@33,@11,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w33+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #429: @7 = (@7+@2) */
  for (i=0, rr=w7, cs=w2; i<6; ++i) (*rr++) += (*cs++);
  /* #430: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #431: @31 = zeros(6x6) */
  casadi_clear(w31, 36);
  /* #432: @11 = @36[18:24] */
  for (rr=w11, ss=w36+18; ss!=w36+24; ss+=1) *rr++ = *ss;
  /* #433: @32 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w32;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #434: @31 = mac(@33,@32,@31) */
  for (i=0, rr=w31; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w33+j, tt=w32+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #435: @32 = zeros(6x6) */
  casadi_clear(w32, 36);
  /* #436: @11 = @22[18:24] */
  for (rr=w11, ss=w22+18; ss!=w22+24; ss+=1) *rr++ = *ss;
  /* #437: @35 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w35;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #438: @17 = @35' */
  for (i=0, rr=w17, cs=w35; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #439: @32 = mac(@17,@33,@32) */
  for (i=0, rr=w32; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w17+j, tt=w33+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #440: @31 = (@31-@32) */
  for (i=0, rr=w31, cs=w32; i<36; ++i) (*rr++) -= (*cs++);
  /* #441: @11 = @36[18:24] */
  for (rr=w11, ss=w36+18; ss!=w36+24; ss+=1) *rr++ = *ss;
  /* #442: @2 = mac(@31,@11,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w31+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #443: @7 = (@7+@2) */
  for (i=0, rr=w7, cs=w2; i<6; ++i) (*rr++) += (*cs++);
  /* #444: @2 = @7' */
  casadi_copy(w7, 6, w2);
  /* #445: @11 = @34[12:18] */
  for (rr=w11, ss=w34+12; ss!=w34+18; ss+=1) *rr++ = *ss;
  /* #446: @1 = mac(@2,@11,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w2+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #447: (@0[2] = @1) */
  for (rr=w0+2, ss=(&w1); rr!=w0+3; rr+=1) *rr = *ss++;
  /* #448: @1 = 0 */
  w1 = 0.;
  /* #449: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #450: @31 = @29' */
  for (i=0, rr=w31, cs=w29; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #451: @2 = mac(@31,@7,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w31+j, tt=w7+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #452: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #453: @31 = @8[36:72] */
  for (rr=w31, ss=w8+36; ss!=w8+72; ss+=1) *rr++ = *ss;
  /* #454: @31 = reshape(@31) */
  /* #455: @11 = @9[12:18] */
  for (rr=w11, ss=w9+12; ss!=w9+18; ss+=1) *rr++ = *ss;
  /* #456: @7 = mac(@31,@11,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w31+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #457: @2 = (@2+@7) */
  for (i=0, rr=w2, cs=w7; i<6; ++i) (*rr++) += (*cs++);
  /* #458: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #459: @29 = zeros(6x6) */
  casadi_clear(w29, 36);
  /* #460: @11 = @36[12:18] */
  for (rr=w11, ss=w36+12; ss!=w36+18; ss+=1) *rr++ = *ss;
  /* #461: @32 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w32;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #462: @29 = mac(@31,@32,@29) */
  for (i=0, rr=w29; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w31+j, tt=w32+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #463: @32 = zeros(6x6) */
  casadi_clear(w32, 36);
  /* #464: @11 = @22[12:18] */
  for (rr=w11, ss=w22+12; ss!=w22+18; ss+=1) *rr++ = *ss;
  /* #465: @17 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w17;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #466: @33 = @17' */
  for (i=0, rr=w33, cs=w17; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #467: @32 = mac(@33,@31,@32) */
  for (i=0, rr=w32; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w33+j, tt=w31+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #468: @29 = (@29-@32) */
  for (i=0, rr=w29, cs=w32; i<36; ++i) (*rr++) -= (*cs++);
  /* #469: @11 = @36[12:18] */
  for (rr=w11, ss=w36+12; ss!=w36+18; ss+=1) *rr++ = *ss;
  /* #470: @7 = mac(@29,@11,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w29+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #471: @2 = (@2+@7) */
  for (i=0, rr=w2, cs=w7; i<6; ++i) (*rr++) += (*cs++);
  /* #472: @7 = @2' */
  casadi_copy(w2, 6, w7);
  /* #473: @11 = @34[6:12] */
  for (rr=w11, ss=w34+6; ss!=w34+12; ss+=1) *rr++ = *ss;
  /* #474: @1 = mac(@7,@11,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w7+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #475: (@0[1] = @1) */
  for (rr=w0+1, ss=(&w1); rr!=w0+2; rr+=1) *rr = *ss++;
  /* #476: @1 = 0 */
  w1 = 0.;
  /* #477: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #478: @29 = @26' */
  for (i=0, rr=w29, cs=w26; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #479: @7 = mac(@29,@2,@7) */
  for (i=0, rr=w7; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w29+j, tt=w2+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #480: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #481: @29 = @8[:36] */
  for (rr=w29, ss=w8+0; ss!=w8+36; ss+=1) *rr++ = *ss;
  /* #482: @29 = reshape(@29) */
  /* #483: @11 = @9[6:12] */
  for (rr=w11, ss=w9+6; ss!=w9+12; ss+=1) *rr++ = *ss;
  /* #484: @2 = mac(@29,@11,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w29+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #485: @7 = (@7+@2) */
  for (i=0, rr=w7, cs=w2; i<6; ++i) (*rr++) += (*cs++);
  /* #486: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #487: @26 = zeros(6x6) */
  casadi_clear(w26, 36);
  /* #488: @11 = @36[6:12] */
  for (rr=w11, ss=w36+6; ss!=w36+12; ss+=1) *rr++ = *ss;
  /* #489: @32 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w32;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #490: @26 = mac(@29,@32,@26) */
  for (i=0, rr=w26; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w29+j, tt=w32+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #491: @32 = zeros(6x6) */
  casadi_clear(w32, 36);
  /* #492: @11 = @22[6:12] */
  for (rr=w11, ss=w22+6; ss!=w22+12; ss+=1) *rr++ = *ss;
  /* #493: @33 = adV(@11) */
  arg1[0]=w11;
  res1[0]=w33;
  if (casadi_f19(arg1, res1, iw, w, 0)) return 1;
  /* #494: @31 = @33' */
  for (i=0, rr=w31, cs=w33; i<6; ++i) for (j=0; j<6; ++j) rr[i+j*6] = *cs++;
  /* #495: @32 = mac(@31,@29,@32) */
  for (i=0, rr=w32; i<6; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w31+j, tt=w29+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #496: @26 = (@26-@32) */
  for (i=0, rr=w26, cs=w32; i<36; ++i) (*rr++) -= (*cs++);
  /* #497: @11 = @36[6:12] */
  for (rr=w11, ss=w36+6; ss!=w36+12; ss+=1) *rr++ = *ss;
  /* #498: @2 = mac(@26,@11,@2) */
  for (i=0, rr=w2; i<1; ++i) for (j=0; j<6; ++j, ++rr) for (k=0, ss=w26+j, tt=w11+i*6; k<6; ++k) *rr += ss[k*6]**tt++;
  /* #499: @7 = (@7+@2) */
  for (i=0, rr=w7, cs=w2; i<6; ++i) (*rr++) += (*cs++);
  /* #500: @7 = @7' */
  /* #501: @2 = @34[:6] */
  for (rr=w2, ss=w34+0; ss!=w34+6; ss+=1) *rr++ = *ss;
  /* #502: @1 = mac(@7,@2,@1) */
  for (i=0, rr=(&w1); i<1; ++i) for (j=0; j<1; ++j, ++rr) for (k=0, ss=w7+j, tt=w2+i*6; k<6; ++k) *rr += ss[k*1]**tt++;
  /* #503: (@0[0] = @1) */
  for (rr=w0+0, ss=(&w1); rr!=w0+1; rr+=1) *rr = *ss++;
  /* #504: output[0][0] = @0 */
  casadi_copy(w0, 6, res[0]);
  return 0;
}

/* MassMatrix:(i0[6],i1[16x7],i2[36x6],i3[6x6])->(o0[6x6]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real **res1=res+1, *rr, *ss;
  const casadi_real **arg1=arg+4;
  casadi_real *w0=w+1275, *w1=w+1311, *w2=w+1317, *w3=w+1323, w4, *w5=w+1330, *w6=w+1336, *w7=w+1339, *w8=w+1345, *w9=w+1457, *w10=w+1673, *w11=w+1709;
  /* #0: @0 = zeros(6x6) */
  casadi_clear(w0, 36);
  /* #1: @1 = input[0][0] */
  casadi_copy(arg[0], 6, w1);
  /* #2: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #3: @3 = zeros(6x1) */
  casadi_clear(w3, 6);
  /* #4: @4 = 1 */
  w4 = 1.;
  /* #5: (@3[0] = @4) */
  for (rr=w3+0, ss=(&w4); rr!=w3+1; rr+=1) *rr = *ss++;
  /* #6: @5 = zeros(6x1) */
  casadi_clear(w5, 6);
  /* #7: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #8: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #9: @8 = input[1][0] */
  casadi_copy(arg[1], 112, w8);
  /* #10: @9 = input[2][0] */
  casadi_copy(arg[2], 216, w9);
  /* #11: @10 = input[3][0] */
  casadi_copy(arg[3], 36, w10);
  /* #12: @11 = pRNE(@1, @2, @3, @1, @5, @3, @6, @7, @8, @9, @10) */
  arg1[0]=w1;
  arg1[1]=w2;
  arg1[2]=w3;
  arg1[3]=w1;
  arg1[4]=w5;
  arg1[5]=w3;
  arg1[6]=w6;
  arg1[7]=w7;
  arg1[8]=w8;
  arg1[9]=w9;
  arg1[10]=w10;
  res1[0]=w11;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #13: (@0[:6] = @11) */
  for (rr=w0+0, ss=w11; rr!=w0+6; rr+=1) *rr = *ss++;
  /* #14: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #15: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #16: @4 = 1 */
  w4 = 1.;
  /* #17: (@2[1] = @4) */
  for (rr=w2+1, ss=(&w4); rr!=w2+2; rr+=1) *rr = *ss++;
  /* #18: @3 = zeros(6x1) */
  casadi_clear(w3, 6);
  /* #19: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #20: @5 = zeros(6x1) */
  casadi_clear(w5, 6);
  /* #21: @7 = pRNE(@1, @11, @2, @1, @3, @2, @6, @5, @8, @9, @10) */
  arg1[0]=w1;
  arg1[1]=w11;
  arg1[2]=w2;
  arg1[3]=w1;
  arg1[4]=w3;
  arg1[5]=w2;
  arg1[6]=w6;
  arg1[7]=w5;
  arg1[8]=w8;
  arg1[9]=w9;
  arg1[10]=w10;
  res1[0]=w7;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #22: (@0[6:12] = @7) */
  for (rr=w0+6, ss=w7; rr!=w0+12; rr+=1) *rr = *ss++;
  /* #23: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #24: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #25: @4 = 1 */
  w4 = 1.;
  /* #26: (@11[2] = @4) */
  for (rr=w11+2, ss=(&w4); rr!=w11+3; rr+=1) *rr = *ss++;
  /* #27: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #28: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #29: @3 = zeros(6x1) */
  casadi_clear(w3, 6);
  /* #30: @5 = pRNE(@1, @7, @11, @1, @2, @11, @6, @3, @8, @9, @10) */
  arg1[0]=w1;
  arg1[1]=w7;
  arg1[2]=w11;
  arg1[3]=w1;
  arg1[4]=w2;
  arg1[5]=w11;
  arg1[6]=w6;
  arg1[7]=w3;
  arg1[8]=w8;
  arg1[9]=w9;
  arg1[10]=w10;
  res1[0]=w5;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #31: (@0[12:18] = @5) */
  for (rr=w0+12, ss=w5; rr!=w0+18; rr+=1) *rr = *ss++;
  /* #32: @5 = zeros(6x1) */
  casadi_clear(w5, 6);
  /* #33: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #34: @4 = 1 */
  w4 = 1.;
  /* #35: (@7[3] = @4) */
  for (rr=w7+3, ss=(&w4); rr!=w7+4; rr+=1) *rr = *ss++;
  /* #36: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #37: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #38: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #39: @3 = pRNE(@1, @5, @7, @1, @11, @7, @6, @2, @8, @9, @10) */
  arg1[0]=w1;
  arg1[1]=w5;
  arg1[2]=w7;
  arg1[3]=w1;
  arg1[4]=w11;
  arg1[5]=w7;
  arg1[6]=w6;
  arg1[7]=w2;
  arg1[8]=w8;
  arg1[9]=w9;
  arg1[10]=w10;
  res1[0]=w3;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #40: (@0[18:24] = @3) */
  for (rr=w0+18, ss=w3; rr!=w0+24; rr+=1) *rr = *ss++;
  /* #41: @3 = zeros(6x1) */
  casadi_clear(w3, 6);
  /* #42: @5 = zeros(6x1) */
  casadi_clear(w5, 6);
  /* #43: @4 = 1 */
  w4 = 1.;
  /* #44: (@5[4] = @4) */
  for (rr=w5+4, ss=(&w4); rr!=w5+5; rr+=1) *rr = *ss++;
  /* #45: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #46: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #47: @11 = zeros(6x1) */
  casadi_clear(w11, 6);
  /* #48: @2 = pRNE(@1, @3, @5, @1, @7, @5, @6, @11, @8, @9, @10) */
  arg1[0]=w1;
  arg1[1]=w3;
  arg1[2]=w5;
  arg1[3]=w1;
  arg1[4]=w7;
  arg1[5]=w5;
  arg1[6]=w6;
  arg1[7]=w11;
  arg1[8]=w8;
  arg1[9]=w9;
  arg1[10]=w10;
  res1[0]=w2;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #49: (@0[24:30] = @2) */
  for (rr=w0+24, ss=w2; rr!=w0+30; rr+=1) *rr = *ss++;
  /* #50: @2 = zeros(6x1) */
  casadi_clear(w2, 6);
  /* #51: @3 = zeros(6x1) */
  casadi_clear(w3, 6);
  /* #52: @4 = 1 */
  w4 = 1.;
  /* #53: (@3[5] = @4) */
  for (rr=w3+5, ss=(&w4); rr!=w3+6; rr+=1) *rr = *ss++;
  /* #54: @5 = zeros(6x1) */
  casadi_clear(w5, 6);
  /* #55: @6 = zeros(3x1) */
  casadi_clear(w6, 3);
  /* #56: @7 = zeros(6x1) */
  casadi_clear(w7, 6);
  /* #57: @11 = pRNE(@1, @2, @3, @1, @5, @3, @6, @7, @8, @9, @10) */
  arg1[0]=w1;
  arg1[1]=w2;
  arg1[2]=w3;
  arg1[3]=w1;
  arg1[4]=w5;
  arg1[5]=w3;
  arg1[6]=w6;
  arg1[7]=w7;
  arg1[8]=w8;
  arg1[9]=w9;
  arg1[10]=w10;
  res1[0]=w11;
  if (casadi_f1(arg1, res1, iw, w, 0)) return 1;
  /* #58: (@0[30:36] = @11) */
  for (rr=w0+30, ss=w11; rr!=w0+36; rr+=1) *rr = *ss++;
  /* #59: output[0][0] = @0 */
  casadi_copy(w0, 36, res[0]);
  return 0;
}

CASADI_SYMBOL_EXPORT int MassMatrix(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int MassMatrix_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int MassMatrix_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void MassMatrix_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int MassMatrix_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void MassMatrix_release(int mem) {
}

CASADI_SYMBOL_EXPORT void MassMatrix_incref(void) {
}

CASADI_SYMBOL_EXPORT void MassMatrix_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int MassMatrix_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int MassMatrix_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real MassMatrix_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* MassMatrix_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* MassMatrix_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* MassMatrix_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    case 3: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* MassMatrix_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int MassMatrix_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21;
  if (sz_res) *sz_res = 8;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 1715;
  return 0;
}

CASADI_SYMBOL_EXPORT int MassMatrix_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 21*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 8*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 1715*sizeof(casadi_real);
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_MassMatrix(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  int mem;
  casadi_real w[2121];
  casadi_int *iw = 0;
  const casadi_real* arg[21] = {0};
  casadi_real* res[8] = {0};
  if (argc>4) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"MassMatrix\" failed. Too many input arguments (%d, max 4)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"MassMatrix\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+406);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+6, casadi_s1, w+406);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+118, casadi_s2, w+406);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+334, casadi_s3, w+406);
  --resc;
  res[0] = w+370;
  MassMatrix_incref();
  mem = MassMatrix_checkout();
  i = MassMatrix(arg, res, iw, w+406, mem);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"MassMatrix\" failed.");
  MassMatrix_release(mem);
  MassMatrix_decref();
  if (res[0]) resv[0] = casadi_to_mex(casadi_s3, res[0]);
}
#endif


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[11];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_MassMatrix(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "MassMatrix")==0) {
    mex_MassMatrix(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'MassMatrix'");
}
#endif
#ifdef __cplusplus
} /* extern "C" */
#endif
